Cargo.toml
fsm/Cargo.toml
fsm/state_machine_procmacro/Cargo.toml
fsm/state_machine_trait/Cargo.toml
src/lib.rs
src/machines/workflow_machines.rs

Also fix dupe license warnings

Rename event_loop to avoid confusion with lang SDK

---

src/lib.rs
src/machines/test_help/mod.rs
src/workflow/concurrency_manager.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

This implements some rather complex (but well encapsulated) concurrency management code to ensure that the workflow machines can be written without needing to be `Send` or `Sync`.
Left to do

Single threaded workflows

---

protos/local/core_interface.proto

This is mostly a placeholder for enabling workflow cancellation work in the Node SDK.

Add CancelWorkflowTaskAttributes

---

protos/local/core_interface.proto
src/lib.rs
src/machines/test_help/history_builder.rs
src/machines/timer_state_machine.rs
src/machines/workflow_machines.rs
src/machines/workflow_task_state_machine.rs

On workflow reset a `WorkflowTaskFailed` with `WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW` cause is written to the history. It contains a new run-id. The new run-id must be used for random seed at this point to avoid producing duplicated UUIDs and random values.
[Here is ](https://github.com/temporalio/sdk-java/blob/30420212a26283cf7cbe6339512058a3186074e8/temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowTaskStateMachine.java#L124) the relevant Java code.

Added randomness seed update on workflow reset

---

.gitignore
src/machines/mod.rs
src/machines/test_help/workflow_driver.rs
src/machines/timer_state_machine.rs
src/machines/workflow_machines.rs
src/workflow/bridge.rs
src/workflow/driven_workflow.rs
src/workflow/mod.rs

This pushes the outgoing jobs queue inside of a new DrivenWorkflow struct which replaces the old trait, and better represents the concepts of needing to fetch from some external workflow code and send it jobs.
This will make sending signals and cancelling much more obvious.

Better encapsulate DrivenWorkflow concept

---

src/lib.rs
src/machines/test_help/mod.rs
src/pollers/mod.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

They were providing little benefit, and this reduces code verbosity.

Collapse ServerGatewayAPIs multiple traits

---

protos/local/core_interface.proto

I'm not sure if we should keep the name `ActivityTask` it might be a bit confusing.
I'm considering changing `activity_id` to just `id` because it should be obvious which ID we mean in the message context.
Not sure if we should wrap `PollActivityTaskQueueResponse` with a `StartActivity` message.

Extend protocol to support activities

---

protos/local/core_interface.proto

StartActivity attributes were pasted from https://github.com/temporalio/api/blob/dfdf839e185089b000dd8613bfea57375088f88a/temporal/api/workflowservice/v1/request_response.proto#L236
I'm not sure if this was the right decision but it's convenient to use.

Make activity task usable

---

src/machines/activity_state_machine.rs
src/machines/test_help/async_workflow_driver.rs
src/machines/workflow_machines.rs

Simple activity state machine tests, similar to those that we have for timer.

Adding state machine tests for activity

---

src/lib.rs
src/machines/activity_state_machine.rs
src/protos/mod.rs
src/test_help/canned_histories.rs
tests/integ_tests/simple_wf_tests.rs

This change adds support for activity failure into the core sdk.
Tested in 3 variations - integ test, lib.rs top level test and state machine test.
Sample history for non-retryable failure case:
```
❯ tctl wf show --wid 1012869045
1  WorkflowExecutionStarted    {WorkflowType:{Name:test-workflow},                           
ParentInitiatedEventId:0,                                     
TaskQueue:{Name:activity_failed_workflow_1964480726,          
Kind:Normal}, WorkflowTaskTimeout:10s,                        
Initiator:Unspecified,                                        
OriginalExecutionRunId:815b9c1e-0893-491f-b35f-20b47b470c72,  
FirstExecutionRunId:815b9c1e-0893-491f-b35f-20b47b470c72,     
Attempt:1, FirstWorkflowTaskBackoff:0s}                       
2  WorkflowTaskScheduled …
```

Activity failure

---

.buildkite/docker/Dockerfile
Cargo.toml
src/lib.rs
src/machines/test_help/mod.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

Public Core APIs are now async
We wanted to have separate APIs for workflow and activity polling, and in order to support single-threaded language SDKs, as well as for ergonomics reasons, using an async API makes sense.
Fixes https://github.com/temporalio/sdk-core/issues/75
Existing tests updated and pass

Asyncify public APIs

---

protos/local/workflow_commands.proto
src/lib.rs
src/machines/activity_state_machine.rs
src/machines/mod.rs
src/machines/test_help/async_workflow_driver.rs
src/machines/test_help/mod.rs
src/machines/timer_state_machine.rs
src/machines/workflow_machines.rs
src/protos/mod.rs
src/test_help/canned_histories.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

WIP
Integ test transitions:
```
tctl wf show --wid 305017165
1  WorkflowExecutionStarted     {WorkflowType:{Name:test-workflow},                           
ParentInitiatedEventId:0,                                     
TaskQueue:{Name:activity_failed_workflow_343899197,           
Kind:Normal}, WorkflowTaskTimeout:10s,                        
Initiator:Unspecified,                                        
OriginalExecutionRunId:6f5fe494-ad26-40a5-bc4b-f6e112f6a6ff,  
FirstExecutionRunId:6f5fe494-ad26-40a5-bc4b-f6e112f6a6ff,     
Attempt:1, FirstWorkflowTaskBackoff:0s}                       
2  WorkflowTaskScheduled        {TaskQueue:{Name:activity_failed_workflow_343899197,          
Kind:Normal}, StartToCloseTimeout:10s, Attempt:1}             
3  WorkflowTaskStarted …
```

Activity cancellation

---

src/lib.rs
src/machines/activity_state_machine.rs
src/test_help/canned_histories.rs
tests/integ_tests/simple_wf_tests.rs

Preview of activity timeout handling in state machines.
There is a bug when timeout happens for canceled activity in try cancel state, it would result in two activations to the lang side (one for cancellation and one for timeout).
We need to discuss and address this issue, ideally as part of this PR.
Also I think I've encountered an issue with test framework and was unable to run activity timeout after cancel test incrementally.

Activity timeout

---

.buildkite/pipeline.yml
.gitignore
Cargo.toml
fsm/state_machine_procmacro/src/lib.rs
fsm/state_machine_trait/src/lib.rs
src/core_tracing.rs
src/machines/activity_state_machine.rs
src/machines/complete_workflow_state_machine.rs
src/machines/fail_workflow_state_machine.rs
src/machines/mod.rs
src/machines/test_help/mod.rs
src/machines/test_help/transition_coverage.rs
src/machines/timer_state_machine.rs

Only when compiled for test, we collect coverage info about which state machine transitions have been hit and turn it into nice little state diagrams with colored lines.
Much easier to tell where we have coverage gaps while testing state machines

Show fsm coverage

---

Cargo.toml

The [patch] directive broke node sdk bridge because it doesn't apply transitively (which https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#working-with-an-unpublished-minor-version explains in a *super confusing* way, sure doesn't look transitive to me). Go back to old way. 

Turns out [patch] doesn't apply to consumers, so, back to old way.

---

README.md
src/core_tracing.rs
src/lib.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/simple_wf_tests.rs
tests/main.rs

Pending activations need to take priority over any currently in-progress but not yet completed poll. This fixes that.
Cancels of activities were getting lost because of the long poll

Make pending activations interrupt long poll

---

protos/local/workflow_activation.proto
src/lib.rs
src/machines/test_help/async_workflow_driver.rs
src/machines/test_help/history_builder.rs
src/machines/test_help/mod.rs
src/machines/workflow_machines.rs
src/protos/mod.rs
src/protosext/history_info.rs
src/test_help/canned_histories.rs
src/workflow/mod.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/simple_wf_tests.rs
tests/main.rs

Workflows are evicted from the cache as soon as they have no more pending activations
Until real sticky task queues are implemented, and we have a proper LRU eviction policy, we need some way to make sure workers don't eat up memory forever, and this is equivalent to the "non sticky" queues in existing SDKs.

Evict workflows after completing a workflow task

---

src/lib.rs
src/machines/test_help/mod.rs
src/machines/test_help/transition_coverage.rs
src/test_help/canned_histories.rs

WFT failures are only reported once until the WFT passes, at which point a new failure may be reported
Needed until proper backoff is implemented, otherwise we can spam server

Only report task failures once (until there is a success)

---

src/lib.rs
src/machines/test_help/mod.rs
src/pending_activations.rs
src/pollers/mod.rs
src/pollers/poll_buffer.rs
src/test_help/canned_histories.rs
src/workflow/mod.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/simple_wf_tests.rs
tests/main.rs

Buffer polls rather than cancelling them when a new pending activation comes in that must be handed out first. Also limit the number of concurrent workflow tasks that may be in flight at one time, and use a per-core-instance task queue rather that per-poll.
Avoid the PA interrupt problem stated in https://github.com/temporalio/sdk-core/issues/91 without the bigger API changes in https://github.com/temporalio/sdk-core/pull/96 .
However, I'm still of the opinion the different API design is ultimately simpler

Buffer poll results rather than cancelling the poll for pending activations

---

Cargo.toml
protos/local/core_interface.proto
src/activity/activity_heartbeat_manager.rs
src/activity/mod.rs
src/errors.rs
src/lib.rs
src/pollers/mod.rs
tests/integ_tests/simple_wf_tests.rs

Implementation of activity heartbeat in the core SDK, which allows lang-side activities to send heartbeat requests rapidly without hitting server on every request. This is possibly because core would aggregate heartbeat requests for up to 1/2 of heartbeat timeout before sending them to the server. Note that first heartbeat request will be sent immediately if core hasn't seen request for the same task token within 1/2 of the heartbet timeout, this means that first heartbeat request for each activity will be sent immediately. Upon shutdown new heartbeat requests will not be recorded and errors will be returned to the core. Outstanding requests will be drained and sent to the server.

Activity heartbeat

---

protos/local/workflow_activation.proto
src/lib.rs
src/machines/test_help/mod.rs
src/machines/workflow_machines.rs
src/pending_activations.rs
src/protos/mod.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

Evictions are now sent to lang -- new pending activities that get queued will collapse jobs if there is already a pending activity with the same ID.
Need to tell lang about cache evictions

Return evictions to lang and also combine pending activity jobs

---

protos/local/core_interface.proto
src/activity/activity_heartbeat_manager.rs
src/activity/details.rs
src/activity/mod.rs
src/errors.rs
src/lib.rs
src/protos/mod.rs
tests/integ_tests/simple_wf_tests.rs

This change makes core memorize heartbeat timeout from the poll activity task response, rather than require it from the lang side.

Remove heartbeat timeout from core heartbeat API

---

src/activity/activity_heartbeat_manager.rs
src/lib.rs
src/pollers/mod.rs
src/pollers/poll_buffer.rs
src/protos/mod.rs

TODO: Buffer poll, other cleanup
Make activity cancels take precedence over polling for new ones
Otherwise workers can get hung on the poll and not see cancels they should

Need to interrupt polling when activity cancels come in

---

src/activity/details.rs
src/lib.rs
src/protos/mod.rs
src/workflow/concurrency_manager.rs

Added test to verify core isn't getting hung up on many concurrent heartbeat cancels.
Also undo issuing pointless activity task for unknown activities.
Better testing around heartbeat concurrency, bench investigation.

Add concurrent heartbeat cancellation test

---

src/lib.rs

Errors returned by the heartbeat, such as validation failures and heartbeat during shutdown are logged and swallowed instead of being returned to the lang.
It has been agreed that this is an optimal behavior for the user to not interrupt activity flow if heartbeat is not working properly.

Log heartbeat errors instead of returning them back to lang

---

protos/local/workflow_activation.proto
src/machines/workflow_machines.rs
src/protos/mod.rs

This is required in order for lang SDKs to be able to dedupe log messages and metrics.
See https://github.com/temporalio/proposals/blob/master/node/logging-and-metrics-for-user-code.md

Add is_replaying attribute to WFActivation

---

protos/local/workflow_activation.proto
src/machines/workflow_machines.rs

Used by interceptors to pass metadata from the client
Tested with the Node SDK

Pass history event header fields to StartWorkflow activation job

---

Cargo.toml
src/core_tests/activity_tasks.rs
src/core_tests/mod.rs
src/core_tests/workers.rs
src/core_tests/workflow_tasks.rs
src/errors.rs
src/lib.rs
src/machines/activity_state_machine.rs
src/machines/test_help/mod.rs
src/machines/workflow_machines.rs
src/pending_activations.rs
src/pollers/mod.rs
src/pollers/poll_buffer.rs
src/protosext/history_info.rs
src/test_workflow_driver.rs
src/worker/mod.rs
src/workflow_tasks.rs
test_utils/src/lib.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/stickyness.rs
tests/integ_tests/workflow_tests/timers.rs
tests/load_tests.rs

Sticky queues are used now when max cached workflows is nonzero
All integ tests were already using a sort of fake sticky mode. Now they use real sticky mode, and some non-sticky tests are added.

Sticky queues implementation

---

src/activity/activity_heartbeat_manager.rs
src/lib.rs
src/test_workflow_driver.rs
src/workflow_tasks.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/stickyness.rs

Make sure we handle the server telling us a task was stale. Previously, completing the WFT would cause the outstanding task to be removed and therefore eviction would not happen.
Fixes a possible bug when dealing with WFT timeouts
1. Closes 
Existing tests now account for this

Fix possible failure to evict when WFT timeout encountered

---

src/machines/workflow_machines.rs

Fixes panic when receiving a query for a workflow which was started on a different worker.

Remove unreachable assertion if reached unexpected workflow execution event

---

Cargo.toml
src/activity/activity_heartbeat_manager.rs
src/activity/details.rs
src/activity/mod.rs
src/core_tests/activity_tasks.rs
src/lib.rs
src/pollers/poll_buffer.rs
test_utils/src/lib.rs
tests/load_tests.rs

No longer warn if we have prior knowledge an activity already doesn't exist according to server.
No spurious warnings
1. Closes 
Against node js bench

Fix unnecessary activity not found warnings when we already know

---

build.rs
src/core_tests/workers.rs
src/lib.rs
src/pollers/poll_buffer.rs

Previously we always began a poll even if there might be pending notification of a task update. Avoid that.
Optimize. Avoid pointless server calls.
1. Closes 

Avoid pointless extra calls to the poll buffer

---

protos/local/child_workflow.proto
protos/local/common.proto
protos/local/workflow_activation.proto
protos/local/workflow_commands.proto
src/machines/child_workflow_state_machine.rs
src/machines/mod.rs
src/machines/transition_coverage.rs
src/machines/workflow_machines.rs
src/protos/mod.rs
src/prototype_rust_sdk.rs
src/prototype_rust_sdk/workflow_context.rs
src/prototype_rust_sdk/workflow_future.rs
src/test_help/canned_histories.rs
src/test_help/history_builder.rs
src/test_help/mod.rs
src/workflow/mod.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/cancel_wf.rs
tests/integ_tests/workflow_tests/changes.rs
tests/integ_tests/workflow_tests/child_workflows.rs
tests/integ_tests/workflow_tests/continue_as_new.rs
tests/integ_tests/workflow_tests/stickyness.rs
tests/integ_tests/workflow_tests/timers.rs
tests/load_tests.rs

Implemented the ChildWorkflowMachine, currently we index child WF machines by their workflow ID which is a bug, @Sushisource let's discuss how we'd change this, we'll need to change it for activities as well.
I suggest we make the correlation ID change later and merge this as is.
For complete child workflow functionality we should implement the external WF machines for cancel and signal.

Implement child workflow state machine

---

protos/local/activity_result.proto
protos/local/child_workflow.proto
src/core_tests/activity_tasks.rs
src/core_tests/workflow_tasks.rs
src/machines/activity_state_machine.rs
src/machines/child_workflow_state_machine.rs
src/protos/mod.rs
src/worker/activities.rs
tests/integ_tests/workflow_tests/activities.rs

Unifies failure handling all across the API, it's a step toward closing https://github.com/temporalio/sdk-node/issues/178.

Use failure for ActivityResult.cancelled, add ChildWorkflowResult.cancelled

---

Cargo.toml
src/core_tests/workflow_tasks.rs
src/lib.rs
src/log_export.rs
src/machines/transition_coverage.rs
src/machines/workflow_machines.rs
src/telemetry/mod.rs
src/workflow/workflow_tasks/concurrency_manager.rs
src/workflow/workflow_tasks/mod.rs

Adds a facility to export logs to lang so that they can show up with the user's configured loggers. Loses some context from tracing but overall still useful.
Easy-to-enable debuggability for users
Relates to https://github.com/temporalio/sdk-core/issues/85

Ability to export logs to lang

---

.buildkite/docker/docker-compose-ci.yaml
.buildkite/docker/docker-compose-telem.yaml
.buildkite/docker/docker-compose.yaml
.buildkite/pipeline.yml
.cargo/config.toml
.gitignore
Cargo.toml
README.md
etc/otel-collector-config.yaml
etc/prometheus.yaml
integ-with-otel.sh
src/lib.rs
src/pollers/retry.rs
src/telemetry/metrics.rs
src/telemetry/mod.rs
src/telemetry/prometheus_server.rs
test_utils/src/lib.rs
tests/integ_tests/client_tests.rs

Expose an option to enable direct scraping of prometheus metrics.
Many users may not care about exporting metrics to the OTel collector, and only use prometheus for metrics. This way they don't have to run the OTel collector if they don't care about traces.
1. Relates to https://github.com/temporalio/sdk-core/issues/85 
Verified metrics are properly exposed on specified endpoint

Allow directly scraping prometheus metrics

---

src/core_tests/queries.rs
src/lib.rs
src/machines/workflow_machines.rs
src/test_help/canned_histories.rs
src/workflow/workflow_tasks/mod.rs
test_utils/src/lib.rs
tests/integ_tests/queries_tests.rs

Fix bug where we could re-apply the final WFT when handling queries after WF is closed
Bugs bad yo
1. Closes #198 
Query test upgraded to verify this

Fix possible re-application of final WFT when querying

---

.buildkite/docker/docker-compose.yaml
src/core_tests/workers.rs
src/lib.rs
src/pollers/gateway.rs
src/pollers/mod.rs
src/telemetry/mod.rs
src/test_help/mod.rs
src/worker/dispatcher.rs
test_utils/src/lib.rs
tests/integ_tests/polling_tests.rs
tests/main.rs

* Also use builder pattern for big options structs
Pass needed headers, getting client name/version from lang
So server can yell at us when we're too old.
1. Closes #76 
Integ tests

Pass required client name/version headers on rpc calls

---

sdk-core-protos/src/lib.rs
src/core_tests/determinism.rs
src/core_tests/mod.rs
src/core_tests/workflow_tasks.rs
src/errors.rs
src/pollers/gateway.rs
src/prototype_rust_sdk.rs
src/prototype_rust_sdk/workflow_future.rs
src/test_help/mod.rs
src/worker/mod.rs
src/workflow/workflow_tasks/concurrency_manager.rs
src/workflow/workflow_tasks/mod.rs

Now errors on workflow completion result in auto-failure of the workflow task. In principle this should only ever be nondeterministic failures, or other edge-case panic type things.
This code can be cleaned up a bit once we do https://github.com/temporalio/sdk-core/issues/171 which I may just do next for exactly that reason, but it will require a bit more work to verify (and should result in Node changes where some code can be removed too)
Seemingly before this change we'd just let WFT time out which I'm slightly surprised by. Now we fail properly, and include the right error code.
1. Closes https://github.com/temporalio/sdk-core/issues/170
Existing and new tests and node integ tests

Automatically fail WFTs when WF code is nondeterministic w/ right cause

---

src/worker/mod.rs
tests/integ_tests/workflow_tests.rs

Previously when completing a workflow task returned "unhandled command" we did not evict. This could lead to potential confusion about workflow state. Now we evict.
1. Closes https://github.com/temporalio/sdk-core/issues/211
Upgraded existing test

Make unhandled command WFT completions trigger an eviction

---

src/core_tests/retry.rs
src/pollers/gateway.rs
src/pollers/retry.rs
tests/integ_tests/workflow_tests/activities.rs

Polling now will retry indefinitely, and ignores cancel/deadline exceeded problems
No reason not to. Polling should retry all transient conditions
1. Closes 
Upgraded / added UTs

Allow long polling to retry indefinitely and under more circumstances

---

.buildkite/docker/Dockerfile
Cargo.toml
fsm/Cargo.toml
fsm/rustfsm_procmacro/Cargo.toml
fsm/rustfsm_procmacro/tests/trybuild/no_handle_conversions_require_into_fail.stderr
fsm/rustfsm_trait/Cargo.toml
sdk-core-protos/Cargo.toml
src/pollers/retry.rs
test_utils/Cargo.toml

Also cargo updates & 2021 edition setting
This is a slightly annoying way to get this done, but it's straightforward and it works.

Log grpc call name when printing retry errors

---

protos/local/workflow_activation.proto
sdk-core-protos/src/lib.rs
src/core_tests/determinism.rs
src/core_tests/workers.rs
src/core_tests/workflow_tasks.rs
src/errors.rs
src/lib.rs
src/pending_activations.rs
src/prototype_rust_sdk.rs
src/test_help/canned_histories.rs
src/test_help/mod.rs
src/worker/mod.rs
src/workflow/mod.rs
src/workflow/workflow_tasks/concurrency_manager.rs
src/workflow/workflow_tasks/mod.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/determinism.rs

We no longer return `WorkflowUpdateError` variants from polling/completing workflow tasks. It put an unnecessary burden on lang to deal with those errors, when the only thing that can really ever happen is to evict them. Now this eviction happens automatically.
* Remove work from lang
* Correctness. Failing a WFT before this change could put the workflow in a stuck state.
TODO:
Closes https://github.com/temporalio/sdk-core/issues/171

Stop returning workflow update errors from poll/complete & auto-evict

---

src/core_tests/child_workflows.rs
src/lib.rs
src/machines/child_workflow_state_machine.rs
src/prototype_rust_sdk.rs
src/prototype_rust_sdk/workflow_context.rs
src/prototype_rust_sdk/workflow_future.rs
tests/integ_tests/workflow_tests/child_workflows.rs
tests/integ_tests/workflow_tests/signals.rs

Before this fix if the test SDK received an activation resolving a child workflow before the workflow code awaited on the result, it would blow up because there was nothing to "resolve" yet.
This problem is now fixed by creating the future for resolution at the same time we start the child wf. 
Bug

Fix issue with receiving child wf result before we awaited for it

---

src/core_tests/mod.rs
src/core_tests/retry.rs
src/pollers/gateway.rs
src/pollers/poll_buffer.rs
src/pollers/retry.rs
src/worker/mod.rs

Apparently polling must specify the queue kind for optimization reasons on server. Fix that.
1. Closes 

Polling needs to specify queue type

---

src/core_tests/workflow_tasks.rs
src/lib.rs
src/machines/activity_state_machine.rs
src/machines/child_workflow_state_machine.rs
src/machines/mod.rs
src/machines/signal_external_state_machine.rs
src/machines/timer_state_machine.rs
src/machines/workflow_machines.rs
src/test_help/canned_histories.rs
src/test_help/history_builder.rs
src/worker/mod.rs

* Fix a situation where we could get stuck polling if WFTs were repeatedly being failed
* Allow lang to send us cancels for already-completed things. This is unavoidable in some situations and we shouldn't blow up. Now they are simply dropped
* Fix for us accidentally still sending commands sometimes for things that were cancelled immediately
Bugs!
1. Closes 
Added tests

Smattering of bugfixes

---

Cargo.toml
src/worker/activities.rs
src/worker/activities/activity_heartbeat_manager.rs
src/worker/config.rs
src/worker/mod.rs

Behavior was incorrect, heartbeats need to be throttled using a timer and not count on Lang to keep sending heartbeats in order to be flushed.
Added 2 new Worker options to control throttling:
* `max_heartbeat_throttle_interval`
* `default_heartbeat_throttle_interval`

Fix activity heartbeat behavior

---

sdk-core-protos/src/lib.rs
src/core_tests/workflow_tasks.rs
src/errors.rs
src/test_help/mod.rs
src/worker/mod.rs
src/workflow/workflow_tasks/mod.rs

While working on LA implementation, discovered that all-internal state machine errors would not avoid spamming WFT failures properly. Fixed that.
:bug: 
1. Closes 

Fix WFT failures sometimes getting stuck in a spam loop

---

src/worker/mod.rs

Move warning message for failed activations to be only during reports

---

src/core_tests/queries.rs
src/machines/workflow_machines.rs
src/test_help/history_info.rs
src/workflow/workflow_tasks/mod.rs

If a workflow is blocked waiting on something and produced an empty WFT, and then is queried, the empty WFT can be double-applied. This fixes that (and any scenario where the WF is cached and we might try to apply events we've already processed) 
:bug: 
1. Closes 

Fix possible application of already-processed history events

---

src/core_tests/activity_tasks.rs
src/worker/activities.rs
src/worker/mod.rs

Shutdown would finish while activities are still running, missing giving the worker a chance to complete any that are outstanding. This can easily hang forever now, so a timeout must be imposed on shutdowns. This can easily be added to core but is currently done in TS.
1. Closes https://github.com/temporalio/sdk-core/issues/246
Tests added / updated

Make shutdown wait on outstanding activity tasks

---

client/src/lib.rs
core/src/core_tests/workers.rs
core/src/worker/mod.rs

Fix scenario where workflow activation polling could return shutdown earlier than it should, when there are still outstanding workflow tasks.
Need to complete outstanding tasks
1. Closes 

Fix possible too-early shutdown case

---

core/src/core_tests/activity_tasks.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_heartbeat_manager.rs
sdk-core-protos/src/lib.rs

Make completion of activities wait on the eviction/flushing of heartbeats before sending a complete.
See https://github.com/temporalio/sdk-core/issues/264
1. Closes https://github.com/temporalio/sdk-core/issues/264
Added test

Fix heartbeats not flushing on activity completion

---

core-api/src/errors.rs
core/Cargo.toml
core/src/core_tests/workflow_tasks.rs
core/src/worker/mod.rs
core/src/workflow/history_update.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/workflow_tasks/mod.rs
sdk-core-protos/src/history_info.rs

Fix unnecessarily failing WFTs when missing the cache by fetching history. This is what other SDKs do.
Less noise for user, marginally more efficient.
1. Closes https://github.com/temporalio/sdk-core/issues/274
Added UT, existing IT.
no

Fetch history on wft cache miss

---

core/src/workflow/machines/mod.rs
core/src/workflow/machines/transition_coverage.rs
core/src/workflow/machines/upsert_search_attributes_state_machine.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/mod.rs
protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
sdk-core-protos/src/lib.rs
sdk/src/workflow_context.rs

Adds support for sending search attribute upsert commands to the server through the UpsertSearchAttributesMachine state machine implementation and related types/transforms.
Feature was missing from sdk-core
1. Closes 
New unit tests

Add upsert search2

---

core/Cargo.toml
core/benches/workflow_replay.rs
core/src/telemetry/mod.rs
core/src/workflow/driven_workflow.rs
core/src/workflow/machines/activity_state_machine.rs
core/src/workflow/machines/child_workflow_state_machine.rs
core/src/workflow/machines/mod.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/machines/workflow_task_state_machine.rs
core/src/workflow/mod.rs
core/src/workflow/workflow_tasks/mod.rs
sdk/src/lib.rs
test-utils/src/canned_histories.rs
tests/integ_tests/workflow_tests/replay.rs

Stops unnecessary cloning of events during WFT application, which can potentially be costly for events with large payloads.
Also added some basic benchmarking
Perf baybeee, and it was easy/fun.

Perf: Avoid cloning events

---

core/src/core_tests/activity_tasks.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/workflow_tasks/mod.rs
sdk-core-protos/src/lib.rs
test-utils/src/lib.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/resets.rs

Problem was the internal run id was always being set to the original
run id, so when it changed because of a reset, lookup of the workflow
state failed
Problem was the internal run id was always being set to the original
run id, so when it changed because of a reset, lookup of the workflow
state failed 
Resets need to work!
1. Closes https://github.com/temporalio/sdk-core/issues/284
Added integration test

Fix resets of workflows causing a panic

---

client/Cargo.toml
client/LICENSE.txt
client/src/lib.rs
core-api/Cargo.toml
core-api/LICENSE.txt
core-api/src/lib.rs
core/LICENSE.txt
core/benches/workflow_replay.rs
core/src/core_tests/child_workflows.rs
core/src/core_tests/determinism.rs
core/src/core_tests/local_activities.rs
core/src/telemetry/mod.rs
core/src/worker/mod.rs
sdk/Cargo.toml
sdk/LICENSE.txt
sdk/src/interceptors.rs
sdk/src/lib.rs
test-utils/Cargo.toml
test-utils/src/lib.rs
tests/integ_tests/workflow_tests/local_activities.rs
tests/integ_tests/workflow_tests/replay.rs
tests/integ_tests/workflow_tests/upsert_search_attrs.rs

Factor out test-only concerns of the SDK worker into the test utils package.
Add more license files / other stuff to crates that needed it
One step on the road to https://github.com/temporalio/sdk-core/issues/222
1. Closes 

Factor out test worker

---

core/src/telemetry/mod.rs
core/src/telemetry/prometheus_server.rs

This attribute was only being set for traces
Helps users filter for temporal metrics
1. Closes 

Ensure `service.name` is set for metrics as well

---

core/src/telemetry/prometheus_server.rs
core/src/worker/activities/activity_heartbeat_manager.rs
sdk-core-protos/src/lib.rs
sdk/src/lib.rs
test-utils/src/lib.rs
tests/integ_tests/heartbeat_tests.rs

It was possible for the very first heartbeat of a new activity task to not be flushed if all the activity does is record the heartbeat and then exit extremely fast, while the server also is slow and takes longer to record the heartbeat than it does to complete the activity.
This happens:
```
| record hb RPC started
|
|    complete activity RPC 
|    |
|    |
|    done
|
| activity not found ?!??
```
Which arguably is also a bit of a server-side bug, but regardless now we make sure the record RPC _completes_ before allowing activity completion.
Bugfix.
Chad noticed while working on Python https://github.com/temporalio/sdk-typescript/issues/538
1. Closes 
New UT/IT

Fix possibly unflushed heartbeats if they are the first heartbeat

---

core/src/core_tests/queries.rs
core/src/workflow/workflow_tasks/mod.rs

Queries arriving with a partial workflow task which also missed the cache would trigger a page fetch and then we would erroneously attach the query job to the activation right then. Instead, replay must complete as normal before we finish the query. Fix that.
Bugs bad!
1. Closes 

Fix bug where partial-task queries could cause us to empty-reply to WFT

---

core/src/abstractions.rs
core/src/core_tests/workflow_tasks.rs
core/src/worker/mod.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/mod.rs
core/src/workflow/workflow_tasks/mod.rs

* Fixed a few situations where extra permits could get added when they shouldn't have been.
* Further mitigate this by not ever going over permit cap
* Noticed and fixed a situation where local activities that were abandoned completing after cancel would enqueue a pending activation that did nothing.
* Also mitigate that by ignoring pending activations that do nothing.
Bugfixing
1. Closes 
Existing tests

Fix extra WFT permits being added in some situations

---

core/src/core_tests/queries.rs
core/src/workflow/workflow_tasks/mod.rs
sdk-core-protos/src/history_info.rs

Super similar to the recent other fix, which failed to account for
the fact that queries might come in with *no* history if the server
still thinks we have the workflow in cache.
Super similar to the recent other fix, which failed to account for
the fact that queries might come in with *no* history if the server
still thinks we have the workflow in cache.
1. Closes 

Fix queries containing *no* history not working

---

core/src/core_tests/local_activities.rs
sdk/src/activity_context.rs
sdk/src/lib.rs
tests/integ_tests/workflow_tests/activities.rs
tests/integ_tests/workflow_tests/local_activities.rs

An activity context that tries to be as close to the go sdk as possible.  Implementation added in sdk/src/activity_context.rs.  sdk/src/lib.rs was also modified to support the new context for each activity worker function.
1. Closes https://github.com/temporalio/sdk-core/issues/301
- Ran Unit Tests
- Ran Integration tests
- Sanity Tested with External Project on Docker-compose temporal environment
Not that I know of.  Would be happy to contribute with some direction.

add activity context for rust sdk

---

.buildkite/docker/docker-compose.yaml
.gitignore
core-api/src/worker.rs
core/src/core_tests/determinism.rs
core/src/core_tests/queries.rs
core/src/core_tests/workers.rs
core/src/core_tests/workflow_tasks.rs
core/src/pending_activations.rs
core/src/test_help/mod.rs
core/src/worker/mod.rs
core/src/workflow/machines/mod.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/workflow_tasks/cache_manager.rs
core/src/workflow/workflow_tasks/concurrency_manager.rs
core/src/workflow/workflow_tasks/mod.rs
sdk/src/interceptors.rs
sdk/src/lib.rs
test-utils/src/lib.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/local_activities.rs
tests/load_tests.rs

* If a new task would overflow the cache, buffer it an instead return an eviction from polling
* Do not allow configuring worker with more concurrent WFTs than the cache limit
* Also fix a bug where we could potentially fail to send a WFT complete to server if the run had a pending eviction
If lang polls faster than it completes, it was possible for it to exceed the cache limit. See added unit test for an example.
1. Closes https://github.com/temporalio/sdk-core/issues/298
Added unit test, new load tests

Fix problems with exceeding cache limit

---

core/src/core_tests/child_workflows.rs
core/src/core_tests/determinism.rs
core/src/core_tests/local_activities.rs
core/src/core_tests/queries.rs
core/src/telemetry/mod.rs
core/src/test_help/mod.rs
core/src/worker/mod.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/workflow_tasks/mod.rs
sdk/Cargo.toml
sdk/src/interceptors.rs
sdk/src/lib.rs
sdk/src/workflow_future.rs
test-utils/src/lib.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/local_activities.rs

This needs a follow up PR to fix a problem that doesn't impact correctness, but could cause bad slowdowns:
Right now we'll evict potentially in the middle of replay. In some cases, that will also cause us to drop the workflow task on the floor, timing it out. This can be fixed by never issuing an eviction until replay is complete and WFT is responded to, but that will require a lot of changes to test code which assumes this all over the place.
* Fixed bug with local activity shutdown
* Fixed another possible empty-commands response while querying if there is also outstanding eviction
* Fixed problem where workflow time is unset if queried before first WFT is started
* Refactored Rust SDK to poll independently of completions
* Bugfixing
1. Closes 
New and existing …

More cache and query fixes

---

bridge-ffi/Cargo.toml
bridge-ffi/src/lib.rs
bridge-ffi/src/wrappers.rs
client/Cargo.toml
client/src/lib.rs
client/src/raw.rs
protos/local/temporal/sdk/core/bridge/bridge.proto
sdk/src/lib.rs
test-utils/src/histfetch.rs
test-utils/src/lib.rs
tests/integ_tests/client_tests.rs
tests/main.rs

Does not address need to set per-call headers, make the Client headers mutable so they can be updated from Lang
Related: #303

Support modifying Client headers

---

core/src/workflow/machines/workflow_machines.rs

When terminating a workflow, the error message read "The event is non a non-stateful event, but we tried to handle it as one.". Should be "The event is not a non-stateful event, but we tried to handle it as one"
For verbosity.
1. Closes 
No.
No

Removed typo in workflow state machines.

---

core/src/core_tests/local_activities.rs
core/src/core_tests/queries.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
test-utils/src/lib.rs

If something went wrong during the processing of a legacy query WFT before core sent the activation to process the query to lang, we would try to respond to the WFT and fail it, rather than responding on the special legacy query API. This fixes that.
Wouldn't properly fail queries when, for example, they triggered a nondeterministic path during replay.
1. Closes 
Added new test

Fix legacy queries not being failed properly if error during replay

---

core/src/abstractions.rs
core/src/core_tests/activity_tasks.rs
core/src/telemetry/metrics.rs
core/src/telemetry/mod.rs
core/src/worker/activities/local_activities.rs
test-utils/src/lib.rs

Add `temporal_` prefix (by default, disableable) to metrics. 
Fix LA slots metric being recorded wrong. Use new better owned permit approach.
This is consistent with other SDKs.
1. Closes 

Add `temporal_` metric prefix, fix LA slot metric

---

core/src/abstractions.rs
core/src/core_tests/activity_tasks.rs
core/src/core_tests/local_activities.rs
core/src/core_tests/workflow_tasks.rs
core/src/test_help/mod.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
tests/integ_tests/queries_tests.rs

Fixed possible race in logic around whether poller should poll or not.
Also make this no longer panic in production code. Temporarily exceeding WFT capacity is better than crashing.
Bug
1. Closes 

Fix possible panic when racing WFT permits

---

bridge-ffi/src/wrappers.rs
client/src/lib.rs
core-api/src/worker.rs
core/src/core_tests/activity_tasks.rs
core/src/lib.rs
core/src/test_help/mod.rs
core/src/worker/mod.rs
protos/local/temporal/sdk/core/bridge/bridge.proto
sdk/src/lib.rs
test-utils/src/lib.rs
tests/main.rs

Moved (and renamed) worker build id to be on worker options, fairly obvious there.
Add ability to override client id from worker options too.
Support https://github.com/temporalio/sdk-typescript/issues/697
1. Closes 

Move worker build id to worker options, allow client id override there

---

core/src/worker/workflow/machines/workflow_machines.rs
sdk/src/workflow_future.rs
tests/integ_tests/workflow_tests/local_activities.rs

Commands that were cancelled after they were "perpared" but *before* they were sent, would be considered cancelled before sent internally, but still got sent to the server. This fixes that.
Fix for https://github.com/temporalio/sdk-typescript/issues/731
1. Closes 

Fix bug where cmds cancelled after prepared but before sent, were sent

---

client/src/lib.rs
client/src/retry.rs
core/src/core_tests/activity_tasks.rs
core/src/core_tests/workers.rs
core/src/lib.rs
core/src/worker/activities/activity_heartbeat_manager.rs
core/src/worker/client.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs

Workers should not bubble up retryable errors as fatal, rather they should prefer to just drop the task and let it expire naturally.
Robustness
1. Closes 
New UT. Can't test specific scenario user reported b/c of Tonic internals, but it's not exactly complex.

Make sure workers do not propagate retryable errors as fatal

---

client/src/lib.rs
client/src/retry.rs
sdk/src/lib.rs
test-utils/src/lib.rs
tests/integ_tests/workflow_tests/signals.rs

```WorkflowClientTrait``` has a new ```signal_with_start_workflow_execution``` method.  ```RetryClient``` and ```Client``` implements this new method.  Added ```ActivityResultPendingError``` to support asynchronous activity completions.
Nice to get closer to parity with other lang sdks.
1. Closes https://github.com/temporalio/sdk-core/issues/359
Integration tests added for this feature in ```tests/integ_tests/workflow_tests/signals.rs```
Not that I am aware of.

implement SignalWithStartWorkflow for client + tests

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/driven_workflow.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/mod.rs
protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
sdk-core-protos/src/lib.rs

Added retry policy field to CAN command.
Carry over memo, search attrs, and retry policy if not specified. (technically :boom: breaking). 
B/c of the maps being at the top level for memo/search attrs, there is not a simple way to just totally wipe the existing value. You'd have to set some pointless "a->a" mapping or something to force the override. Maybe we want to change that.
Retry policy is needed
Carrying over the fields mentioned just generally makes sense.
1. Closes https://github.com/temporalio/sdk-core/issues/372
Added UT

Add retry policy to continue-as-new, and carry over current WF values

---

client/src/lib.rs

Expose `HealthService` trait via client API so it can be used by callers.
1. Closes #385

Expose HealthService

---

core/Cargo.toml
core/src/ephemeral_server/mod.rs

For the Java-based-Graal-built ephemeral test server, we are manually doing https://linux.die.net/man/2/waitpid because for whatever reason Tokio is not doing it properly leaving a zombie process around. Unfortunately I cannot replicate in Rust integration tests.
See #391. Basically `child.kill().await` leaves zombies around in certain cases.
1. Closes #391

Fix for ephemeral test server zombie

---

core/Cargo.toml

Removes the dependency on system's libssl (usually openssl) which complicates cross compilation.

Use tokio-rustls for reqwest

---

client/src/lib.rs
client/src/retry.rs
core-api/src/errors.rs
core/src/worker/activities.rs
core/src/worker/client.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs

No completion errors will ever crash the worker
Long poll permits "fatal" errors for up to a minute
Sometimes infrastructure pieces return stupid error codes, and we shouldn't crash in that case, even if things are telling us the error is fatal. Those things are stupid and wrong, but, so be it.
1. Closes 
Existing UTs

Protect worker from more network errors

---

.gitignore
client/src/lib.rs
client/src/raw.rs
client/src/retry.rs

Polling wasn't retrying forever properly because of a stupid string naming mistake. Fixed.
Unfortunately there wasn't really any reasonable way to UT this specific thing without either feeling performative (string == string I just wrote, which are both constants) or hilariously overkill (in memory fake grpc server, which currently isn't compiled).
So, strings are lifted into constants and doc'd better.
Bug
1. Closes 
Existing uts

Fix incorrect string names for polling methods (oops)

---

.buildkite/pipeline.yml
.cargo/config.toml
bridge-ffi/src/lib.rs
client/src/raw.rs
core/Cargo.toml
core/src/ephemeral_server/mod.rs
core/src/pollers/mod.rs
core/src/telemetry/mod.rs
core/src/worker/client/mocks.rs
test-utils/src/lib.rs
tests/integ_tests/ephemeral_server_tests.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/queries_tests.rs
tests/integ_tests/workflow_tests/replay.rs
tests/integ_tests/workflow_tests/upsert_search_attrs.rs
tests/main.rs
tests/runner.rs

Temporalite is now used by default when running integ tests. CI still uses docker (for now, I will add temporalite additionally shortly). Java Test server is supported, but breaks many tests.
No more docker or manually setting things up / stopping them when running integ tests, yay!
1. Closes 
Existing tests

Auto-start of temporalite & testsrv for integ tests

---

client/src/lib.rs
core-api/src/worker.rs
core/benches/workflow_replay.rs
core/src/abstractions.rs
core/src/core_tests/local_activities.rs
core/src/core_tests/queries.rs
core/src/core_tests/workflow_tasks.rs
core/src/lib.rs
core/src/replay/mod.rs
core/src/test_help/mod.rs
core/src/worker/client.rs
core/src/worker/client/mocks.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
sdk-core-protos/src/history_builder.rs
sdk-core-protos/src/history_info.rs
test-utils/src/lib.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/replay.rs

Implemented ability to provide multiple histories when constructing a replay worker
More efficient and easier to use than creating many workers lang side
1. Closes 
Existing / new tests

Implement multiple histories support for replaying

---

client/src/lib.rs
client/src/retry.rs

Backoff more aggressively if we receive a  ResourceExhausted error from the server. implementation based on the suggestion from the server team .
```
Here is an example of how it can be handled just to give some idea:
https://github.com/temporalio/temporal/blob/3182dc2cde75e3e49fccb1de2905db5d30db58ab/common/backoff/retry.go#L204-L206
```
See also: https://github.com/temporalio/sdk-features/issues/96
closes https://github.com/temporalio/sdk-core/issues/406

Backoff more if we receive ResourceExhausted error

---

core/src/worker/workflow/machines/child_workflow_state_machine.rs

User ran into `Invalid transition while attempting to cancel ChildWorkflowMachine in StartFailed` -- there's no reason to blow up in this case.

Ignore cancels of StartFailed state in child workflows

---

core/src/telemetry/metrics.rs
core/src/worker/workflow/driven_workflow.rs
core/src/worker/workflow/machines/workflow_machines.rs
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/lib.rs

Expose workflow start time in start workflow activation job
Useful for some interceptor-based scenarios, etc. Should be exposed under unsafe area.
1. Closes 

Expose workflow start time

---

core/src/replay/mod.rs
tests/integ_tests/workflow_tests/replay.rs

* Just explicitly evict after every finished run
Made it possible to supply multiple histories with the same run id to the replayer
Better than having to silently skip or fail early
1. Closes 

Figured out a reasonable way to make dupe run-ids work during replay

---

core/src/lib.rs

Use a per-worker random id rather than process-wide.
I guess if you're a weirdo and you want to run multiple workers on the same queue in the same process :wink: 
1. Closes https://github.com/temporalio/sdk-core/issues/428

Don't use a process-wide unique id for sticky queues

---

.buildkite/docker/Dockerfile
core/src/abstractions.rs
core/src/core_tests/activity_tasks.rs
core/src/core_tests/local_activities.rs
core/src/core_tests/workers.rs
core/src/core_tests/workflow_cancels.rs
core/src/core_tests/workflow_tasks.rs
core/src/telemetry/log_export.rs
core/src/worker/activities/local_activities.rs
core/src/worker/workflow/driven_workflow.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
fsm/rustfsm_procmacro/tests/trybuild/no_handle_conversions_require_into_fail.stderr

Never send a legacy query with other jobs
It's illegal. Other jobs can trigger new commands, and a legacy query activation can never be responded to with other commands, and I promise I'll never do it (oops)
1. Closes https://github.com/temporalio/sdk-core/issues/426
New test

Fix and add test for sending activation w/ legacy query + other job

---

core/src/lib.rs
core/src/telemetry/log_export.rs
core/src/telemetry/mod.rs

See title
Makes it easier to set trace subscriber for, ex, multithreaded tokio runtimes.
1. Closes 

Create a helper for setting the trace subscriber for the current thread

---

core/src/lib.rs

Silly oversight. This is needed to fetch logs.

Add a method to get ref to telem instance from runtime

---

sdk-core-protos/src/lib.rs

This metric was using original attempt schedule time rather than current attempt.
Align with other SDKs, enables resolving https://github.com/temporalio/sdk-typescript/issues/972

Fix activity scheduled_to_start_latency metric

---

core/Cargo.toml
sdk/Cargo.toml

I've Removed the `always-log` feature from all `tracing` dependencies in order to fix a double logging issue.
If a consumer of the `temporal-sdk` or `temporal-sdk-core` crates initializes a tracing-subscriber it will begin double-logging everything. I'm still not 100% sure why it happens but it seems to be something link-time related from the tracing crate. You can reproduce the problem just by including `temporal-sdk-core` in Cargo.toml.
Built a simple reproduction:
```rust
fn main() {
tracing_subscriber::fmt::init();
tracing::info!("should not be double");
}
```
With `always-log` enabled in sdk and core running this code will double log. If the feature is removed it will not.

Remove always-log feature from sdk and core to prevent double logging

---

sdk-core-protos/src/lib.rs
sdk/Cargo.toml
sdk/src/lib.rs
tests/integ_tests/workflow_tests/activities.rs

Added a `NonRetryableActivityError` type so that an ActivityFunction can return this Error and the activity is not retried. Hence, the workflow will fail.
To be able to accommodate for the use-case where you as the user *know* that the activity should not be retried.
1. Closes: https://github.com/temporalio/sdk-core/issues/454
Test was added `activity_non_retryable_failure_with_error` that uses the new function: `Failure::application_failure_from_error`.
Also, created a manual test locally: Where an activity was used that returns the **new** error type. Not sure if a test could be added to `local_activities` to properly test the error conversion code? Could use some pointers here if this is deemed necessary :) Thanks!
Not sure, as there …

Added the option to have the activity return a non-retryable error.

---

client/src/lib.rs
client/src/retry.rs
core/Cargo.toml
tests/integ_tests/visibility_tests.rs
tests/integ_tests/workflow_tests/signals.rs

- Added helper struct `SignalWithStartOptions` that also derives a builder
- Added client calls for `list_archived_workflow_executions`
The parameter list for `client.signal_with_start_workflow_execution` was growing out of control.
1. Closes 
integration tests using this call was updated to use the builder.
no

add SignalWithStartOptions and builder

---

core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/mod.rs
tests/fuzzy_workflow.rs

This fixes a bug I discovered and was able to make reproducible with the work in https://github.com/temporalio/sdk-core/pull/469
(and also needs that PR to be merged first, draft until it is)
The problem was introduced in https://github.com/temporalio/sdk-core/pull/463 which refactored history updates / pagination. 
The concept of the last started WFT id must be preserved as it was told to us according to server when we started the *current* workflow task. However, I intermixed the concept of the last processed ID as according to state machines with that value, because they're typically used for the same purpose - except in one important spot, determining when replay is finished.
It was possible when missing the cache to reset the last started WFT id to zero, because that is where we …

Fix forgetting correct value for previous WFT started ID

---

.github/workflows/heavy.yml
core/src/core_tests/activity_tasks.rs
core/src/core_tests/determinism.rs
core/src/core_tests/local_activities.rs
core/src/core_tests/queries.rs
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/patch_state_machine.rs
sdk-core-protos/src/history_builder.rs
sdk-core-protos/src/history_info.rs
sdk-core-protos/src/lib.rs
test-utils/src/canned_histories.rs
test-utils/src/lib.rs
tests/integ_tests/heartbeat_tests.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/workflow_tests/activities.rs

If an activity scheduled command has a different type from the scheduled event in history matching that sequence number, we'll now fail w/ nondeterminism as we always should've.
Turns out, the check that their ids match is also missing, which is less surprising than it sounds since we already do sequence number checks and in almost all cases the ID == the sequence number, but that's been fixed as well.
Also did a bunch of semi-related mechanical cleanup to test construction. You can look at only the first & last commit diffs to see relevant changes.
Previous behavior was wrong.
1. Closes https://github.com/temporalio/sdk-core/issues/443
Added test, existing tests.

Make activity type / id mismatches a nondeterministic change

---

core/src/core_tests/local_activities.rs
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_extraction.rs
core/src/worker/workflow/workflow_stream.rs
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
tests/runner.rs

If fetching pages failed while in the middle of an activation completion, that could leave the completion stuck because the eviction wouldn't unblock it. This fixes that.
Bug
1. Closes 

Fix failed fetch request not unblocking completion

---

core/src/abstractions.rs
core/src/telemetry/mod.rs
core/src/telemetry/prometheus_server.rs
core/src/worker/activities.rs
core/src/worker/activities/local_activities.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_extraction.rs
tests/integ_tests/metrics_tests.rs

See title
Though in some sense correct, the fact that we pre-reserve slots is confusing to users looking at metrics.
1. Closes https://github.com/temporalio/sdk-core/issues/474

Fix slot metrics appearing to be off-by-one because of reservation

---

client/src/lib.rs
client/src/metrics.rs
core-api/Cargo.toml
core-api/src/telemetry.rs
core/src/lib.rs
core/src/telemetry/metrics.rs
core/src/telemetry/mod.rs
tests/integ_tests/metrics_tests.rs
tests/main.rs

Client metrics were emitted missing this prefix, by accident.
Not what we say on the tin.
1. Closes https://github.com/temporalio/sdk-core/issues/483
Existing test
Potentially a breaking change for users depending on the incorrect names. There is an existing flag to not use the prefix, but that'll apply to _all_ metrics, including ones that maybe they expected to find the prefix on. 
IMO, we should go with this and just call it out in release notes, as emitting multiple metrics is uggo - but if needed we can add _another_ flag for specifically this issue.

Fix client metrics lacking the `temporal_` prefix

---

protos/local/temporal/sdk/core/activity_result/activity_result.proto
protos/local/temporal/sdk/core/activity_task/activity_task.proto
protos/local/temporal/sdk/core/child_workflow/child_workflow.proto
protos/local/temporal/sdk/core/common/common.proto
protos/local/temporal/sdk/core/core_interface.proto
protos/local/temporal/sdk/core/external_data/external_data.proto
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
protos/local/temporal/sdk/core/workflow_completion/workflow_completion.proto

- Add `option ruby_package` on all coresdk proto files
- Ruby convention for module name is camel case. This was previously fixed manually in sdk-ruby

Add Ruby package option to coresdk protos

---

.buildkite/docker/docker-compose.yaml
core/src/internal_flags.rs
core/src/test_help/mod.rs
core/src/worker/workflow/machines/patch_state_machine.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run/managed_wf_test.rs
sdk-core-protos/src/history_builder.rs

* Auto-create an upsert command for the `TemporalChangeVersion` SA upon patched calls
* Warn & don't do that if it would exceed SA size limit
* Nondeterminism checking for upsert calls
Parity + Safety
1. Closes https://github.com/temporalio/sdk-core/issues/492
Added UTs / existing UTs & ITs
We will need lang release notes to mention the determinism changes & the fact that writing/reading the `TemporalChangeVersion` attribute from workflow code is a no-no.

Auto-upsert versions SA on patched calls & nondeterminism check for upserts

---

core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/cancel_external_state_machine.rs
core/src/worker/workflow/machines/cancel_workflow_state_machine.rs
core/src/worker/workflow/machines/child_workflow_state_machine.rs
core/src/worker/workflow/machines/complete_workflow_state_machine.rs
core/src/worker/workflow/machines/continue_as_new_workflow_state_machine.rs
core/src/worker/workflow/machines/fail_workflow_state_machine.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/mod.rs
core/src/worker/workflow/machines/modify_workflow_properties_state_machine.rs
core/src/worker/workflow/machines/patch_state_machine.rs
core/src/worker/workflow/machines/signal_external_state_machine.rs
core/src/worker/workflow/machines/timer_state_machine.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs
core/src/worker/workflow/machines/workflow_task_state_machine.rs
fsm/rustfsm_procmacro/src/lib.rs
fsm/rustfsm_trait/src/lib.rs

This had just been bugging me for a while. Needless copying going on. Will improve perf, probably not by much, but in some pathological cases it could make a real difference.
Side bonus, ended up with less code.

Stop cloning state machines on every transition

---

client/src/metrics.rs
core-api/src/lib.rs
core-api/src/worker.rs
core/src/abstractions.rs
core/src/abstractions/take_cell.rs
core/src/core_tests/activity_tasks.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_heartbeat_manager.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs
protos/local/temporal/sdk/core/activity_task/activity_task.proto
tests/integ_tests/workflow_tests/activities.rs

Auto-issue cancels for activities still running past a grace period
Lang layer is implementing this right now
1. Closes https://github.com/temporalio/sdk-core/issues/493
UT/IT

Graceful shutdown for activities

---

core-api/src/worker.rs

More convenient to use from lang since we don't need to conditionally set the option.

Remove setter(strip_option) for graceful_shutdown_period worker option

---

core/src/core_tests/activity_tasks.rs
core/src/core_tests/local_activities.rs
core/src/core_tests/workers.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs

Fix shutting down the LA manager a bit too early. Now we wait for workflows to shutdown first.
If you completed a task with a new LA request, that would all just get dropped, now it doesn't.
1. Closes 

Ensure LA tasks can be delivered during shutdown

---

core/Cargo.toml
core/src/telemetry/mod.rs

Disclaimer:
I'm not a Rust developer and this draft is more of a proposal to check for two things:
1. Would this be valuable for the sdk-core? We are trying to use sockets in our organization and already do it for DogStatsd. Using TCP would require doing so at an org level.
2. Whether this is a sound implementation. It looks fairly reliable logic-wise but it does add one more code branch. Maybe there's a better way to do this more easily.
I also only focused on metrics because that's what we care about.
Handle 'unix' schema for metrics
Currently, sdk-core only supports grpc over tcp while some collectors allow UDS usage.
Sadly `tonic` does not support connecting to `unix` schema natively.
1. Closes N/A
4. How was this tested:
Testing in progress (no longer getting invalid schema but have …

Add support for metrics over UDS

---

core/src/ephemeral_server/mod.rs

Workaround for incompatibility of zip files generated by goreleaser and zip-rs.
See: https://github.com/zip-rs/zip/issues/108

Prefer tar.gz format for CLI download

---

core/Cargo.toml
core/src/telemetry/mod.rs

Reverts temporalio/sdk-core#507
For context:
In additional testing I found that there is a bug in opentelemetry-otlp library.
It does not respect `with_channel` for _metrics_ as of now (and falls back to default endpoint)
I may try to fix it there if I have resources but I want to revert this for now to avoid the confusion I've gone through (I have a local bandaid but a proper fix needs much more polish).
To clarify: the traffic I saw in my initial testing turned out to be the connection opening with an immediate 'GOAWAY' frame (as the channel presumably gets immediately "collected").
I mistakenly thought that the traffic I saw initially contained metrics that we failed to ingest on _our_ end.
I will revisit this if\when opentelemetry-otlp has a fix for this.
Thank you again for a speedy …

Revert "Add support for metrics over UDS"

---

.buildkite/docker/Dockerfile
.buildkite/pipeline.yml
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_extraction.rs
core/src/worker/workflow/workflow_stream.rs
sdk-core-protos/src/history_info.rs
sdk-core-protos/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_future.rs

It was possible to hit a case where core would fail to realize it needed to fetch more events and instead apply partial history, with an incorrect length.
This fixes that.

Fix possible incorrect history length value

---

sdk/src/workflow_future.rs

No reason to do this and crash the worker, even if they aren't implemented.

Don't panic in Rust SDK on queries

---

core-api/src/telemetry.rs
core/src/telemetry/mod.rs
core/src/telemetry/prometheus_server.rs

Add support for passing a map of tags for metrics and traces
Currently - core SDK uses a single `service.name` tag (that cannot be overriden)
Many users, however, may want to supply their own (for example, to identify service or host running a worker or making client requests)
1. Closes #467
Tested with a local otel collector and temporal SDK python.
Note: I used an older commit because python does not seem to compile with latest SDK.
Ensured a custom tag set in Python gets propagated to the collector (along service.name tag)
Did not test prometheus as we don't use it but can upon request
Probably not
We don't use opentelemetry so maybe variables aren't most aptly named so open to feedback on that (in datadog these are just tags)
Also, I …

Add support for global metric and tracing tags

---

core/src/core_tests/determinism.rs
core/src/internal_flags.rs
core/src/worker/mod.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
tests/integ_tests/workflow_tests/determinism.rs

1. Avoid a possible panic where if core was autocompleting some WFT because it encountered an error internally (ex: nondeterminism) while there was also an outstanding eviction, that autocomplete would trigger the eviction to finish even though lang hadn't replied to the eviction activation. Later, when we got that reply from lang, we freaked out because the workflow was no longer in cache.
2. Checking determinism for SA values is silly and overkill so we stopped
Bug bad, SA determinism check too persnickety for little payoff.
1. Closes https://github.com/temporalio/sdk-core/issues/526
Added UT that triggered the panic.

Avoid possible panic on autocompleting WFTs due to failure, and stop checking SA values for determinism

---

.gitignore
client/src/lib.rs
tests/main.rs

Allow overriding origin for connections
When connecting via a proxy to cloud, just changing the domain for TLS verification is only part of the puzzle. Additionally, our stuff expects to see the right `:authority` and/or `host` headers set. Setting the origin value for the connection handles that.
1. Closes 

Allow overriding origin for core connections

---

core/src/worker/workflow/history_update.rs
sdk/src/workflow_context.rs
sdk/src/workflow_context/options.rs

It was possible to drop events that were in a WFT but not in the history fetch request in the event that pagination ends up being required.
Bug
1. Closes 

Fix possibly dropping final events in a WFT during cache miss

---

.buildkite/pipeline.yml
.cargo/config.toml
CODEOWNERS
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/managed_run/managed_wf_test.rs

More fixes for everyone's favorite spot of code. This time, we handle the fact that we could consider workflow task sequences as complete if we just happen to have history which ends on a WFT started event - but that's not sufficient. If we know there might be more events, we need to peek beyond the started event to see if the next event is a task failure, or a heartbeat, etc.
Bugs!
1. Closes 

Fix more pagination insanity

---

README.md
core/src/core_tests/local_activities.rs
core/src/worker/workflow/managed_run/managed_wf_test.rs
sdk/src/lib.rs
sdk/src/workflow_future.rs
tests/integ_tests/workflow_tests/child_workflows.rs

1) Modified SDK to handle 'Payload' as the return value of workflow function instead of an empty tuple.
2) Updated tests
A step towards https://github.com/temporalio/sdk-core/issues/222
1. This part of work in https://github.com/temporalio/sdk-core/issues/539
Updated tests and added new tests
No

Updated workflow function to return Payload instead of empty tuple

---

core-api/src/worker.rs
core/src/abstractions.rs
core/src/core_tests/activity_tasks.rs
core/src/core_tests/workers.rs
core/src/core_tests/workflow_tasks.rs
core/src/pollers/mod.rs
core/src/pollers/poll_buffer.rs
core/src/test_help/mod.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_task_poller_stream.rs
core/src/worker/mod.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_extraction.rs
core/src/worker/workflow/wft_poller.rs
test-utils/src/lib.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/activities.rs
tests/integ_tests/workflow_tests/continue_as_new.rs
tests/integ_tests/workflow_tests/stickyness.rs

Remove the semaphore that restricted concurrent polls based on requests. This in practice meant we were typically limited to one concurrent poll, except in some situations where polls get put in buffers.
Closer to what other SDKs are doing, allows for some concurrency scale-up without getting clever yet, which we'll do later.
1. Closes https://github.com/temporalio/sdk-core/issues/546

Poll concurrently at will

---

core/src/telemetry/metrics.rs
core/src/worker/workflow/run_cache.rs

Exists in Go / Java and useful for determining if cache size is too small

Add the `sticky_cache_total_forced_eviction` metric

---

.github/workflows/heavy.yml
cargo-tokio-console.sh
core-api/src/worker.rs
core/Cargo.toml
core/src/core_tests/workflow_tasks.rs
core/src/pollers/poll_buffer.rs
core/src/telemetry/mod.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_task_poller_stream.rs
core/src/worker/mod.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/workflow_tests/stickyness.rs

Move ratelimiter capability inside pollers to make activity ratelimiting work properly with concurrent pollers
Recent change to make pollers genuinely concurrent could cause task timeouts in the event users have enabled ratelimiting
1. Closes 
Existing UT made more accurate w/ mock client rather than mock poller

Apply rate limiter at the poller level

---

core/Cargo.toml
core/src/lib.rs
test-utils/Cargo.toml

Added a feature flag for ephemeral server functionality.
To optimize compilation time for pure Rust usage of SDK.
This is same as https://github.com/temporalio/sdk-core/pull/560 but without default
1. Closes #559
Run the existing unit/integration/load tests, 
No

Added feature flag for ephemeral server module

---

core/src/protosext/mod.rs
core/src/worker/workflow/driven_workflow.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/mod.rs

No need for this timeout fallback since you're made to set either one of the appropriate timeouts anyways, and the workflow execution timeout being zero could cause issues.

Remove fallback to workflow execution timeout for LA sched-to-close

---

core/src/worker/workflow/machines/workflow_machines.rs
test-utils/src/lib.rs
tests/integ_tests/metrics_tests.rs

Only emit these metrics for terminal WF commands when not replaying
Previous behavior is not intentional or useful.
1. Closes 

Don't increment terminal command metrics when replaying

---

protos/google/rpc/status.proto

- Add a local copy of proto definition for [google.rpc.Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto)
- This is required to decode the `grpc-status-details-bin` metadata contained in errors sent by the server.
- Given that Java SDK would also need a copy of this, we could instead add this into the `api` repo. However, we add the health service protos in this repo rather that the`api` repo, so maintaining coherence.

Add google/rpc/status.proto

---

core/src/worker/workflow/mod.rs

Ref #521 cc @mjameswh @Sushisource 
Minor tweak to warning message in fall-through case. This case handles a variety of conditions including application-level errors such as bad search attributes, so "Network error" is misleading.

Improve warning message on error response to completion

---

core/src/worker/workflow/machines/patch_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
sdk/src/workflow_context.rs
tests/integ_tests/workflow_tests/patches.rs

Permit the removal of deprecated patch calls which are immediately adjacent to another patch call.
This was done by allowing patch-id-mistmaches in when checking a patch event against a patch machine, if the event is deprecated. I do not see this as a risky change primarily because nondeterminism checking of this kind purely serves as an "early warning" against other subsequent nondeterminism which would happen as a result of taking the incorrect branch. So, although this change technically means you could swap out one deprecated patch for another and there would be no error on that line - you'd still likely encounter another one later as if you hadn't used patching at all.
I think this is an acceptable tradeoff, since I cannot think of any other way to make this work and at least a …

Fix removal of deprecated patch call adjacent to other patch

---

client/Cargo.toml
client/src/lib.rs
client/src/metrics.rs
client/src/raw.rs
core-api/Cargo.toml
core-api/src/telemetry.rs
core-api/src/telemetry/metrics.rs
core-api/src/worker.rs
core/Cargo.toml
core/src/lib.rs
core/src/telemetry/metrics.rs
core/src/telemetry/mod.rs
core/src/telemetry/prometheus_server.rs
core/src/worker/mod.rs
test-utils/src/lib.rs
tests/integ_tests/metrics_tests.rs
tests/main.rs

This takes a crack at what it will look like to export metrics to lang.
DRAFT since it's still subject to change, though the existing implementation being backed by the new interface does work.

Lang metrics export

---

core/src/lib.rs
core/src/telemetry/mod.rs
tests/integ_tests/metrics_tests.rs

Allows the starting of the prometheus server after initializing the Core runtime so Tokio will exist.
Panic bad
1. Closes 

Allow attaching metric meters late

---

core/src/core_tests/replay_flag.rs
core/src/worker/workflow/machines/workflow_machines.rs

In some situations server could issue WFTs with queries that also contained the last WFT complete & associated commands. This would confuse the code that determines if we are replaying or not.
Also make all activations containing only queries always be replay.
Fixes incorrect semantics
1. Closes https://github.com/temporalio/sdk-core/issues/589
Added UT, verified existing tests. Fixes James' repro in the bug.

Fix query related is_replay flag error

---

Cargo.toml
core-api/src/telemetry/metrics.rs
core/Cargo.toml
core/src/internal_flags.rs
core/src/lib.rs
core/src/telemetry/log_export.rs
core/src/telemetry/metrics.rs
core/src/telemetry/mod.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
sdk/src/workflow_context.rs
test-utils/src/lib.rs

Do not register a trace subscriber on threads unless the telemetry config actually asked to do anything.
Causes problems with user created global subscribers
1. Closes https://github.com/temporalio/sdk-core/issues/601
Existing tests

Only set trace subscriber when useful

---

core/src/core_tests/local_activities.rs
core/src/core_tests/queries.rs
core/src/core_tests/replay_flag.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
test-utils/src/lib.rs
tests/integ_tests/workflow_tests/local_activities.rs

Queries now always go in their own activation
We agreed this is the most reasonable way to disambiguate the `is_replaying` flag.
1. Closes https://github.com/temporalio/sdk-core/issues/600
Existing / new tests

Separate activations for queries

---

client/src/lib.rs

Exposed keep alive options, and defaulted them to enabled with 30s interval and 15s timeout by default. See https://github.com/temporalio/features/issues/123.
1. Closes #585

Client keep alive, enabled by default

---

client/src/metrics.rs
core-api/src/telemetry/metrics.rs
core/src/telemetry/metrics.rs
core/src/telemetry/mod.rs

Added `CustomMetricAttributes` trait / variant to `MetricAttributes` to allow langs to have a simple reference based approach to allocating their own attributes.
Allows destroying backing attributes on `Drop` of the thing implementing `CustomMetricAttributes`
It may no longer be worth keeping a buffer at all, or, if we do, I need to re-implement it to work in terms of refs.
1. Closes 
Existing tests

Allow `CoreMeter` implementations to use their own custom attribute reference

---

client/src/lib.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/run_cache.rs
sdk/src/workflow_future.rs
tests/integ_tests/update_tests.rs

The main fix resolves a problem where Core was sending a WFT complete too early when updates were included in the first WFT, causing a WFT failure spam loop if the update failed a task.
Also fix some dangling TODOs from the first PR
Yummy fixes
1. Closes 

Workflow Update small fixes

---

core/src/core_tests/workflow_tasks.rs
core/src/protosext/mod.rs
core/src/worker/mod.rs
core/src/worker/workflow/machines/workflow_machines.rs
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/history_builder.rs
sdk-core-protos/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_future.rs

Add current build id as a field on workflow activations
So users can tell during replay what build id was used to process the current task.
1. Closes https://github.com/temporalio/features/issues/253
Added unit test

Attach current Build ID to workflow activations

---

client/src/workflow_handle/mod.rs
core/src/ephemeral_server/mod.rs
core/src/worker/workflow/machines/update_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
test-utils/src/lib.rs
tests/integ_tests/update_tests.rs
tests/runner.rs

Core would fail to send a protocol message if we began the processing of an update while replaying, but finished replay before finishing it.
:boom: Also added stderr output setting for embedded server because I was SO TIRED of server logspam, which all comes on stderr anyways apparently.
1. Closes 

Bugfix for failure to send protocol msg when resuming unfinished updates

---

core-api/src/telemetry.rs
core/src/telemetry/log_export.rs
core/src/telemetry/mod.rs

Create a new Telemetry option `temporal_sdk_core_api::telemetry::Logger::Push` which accepts a filter like the others, but also accepts an implementation of the `CoreLogConsumer` trait which is a simple single-function trait invoked for each log.
Also exposed a `temporal_sdk_core::telemetry::CoreLogBufferedConsumer` struct which, upon `new`, will return itself (an implementation of `CoreLogConsumer`) and a `temporal_sdk_core::telemetry::CoreLogBuffer` upon which `drain` can be invoked. Also altered log forwarding to leverage the new abstraction which means the foward.
Also expose a `temporal_sdk_core::telemetry::CoreLogStreamConsumer` that is backed by a bounded mpsc channel.
For langs where they need to buffer/throttle on a max-frequency, they are expected to use …

Log pushing support

---

core-api/src/worker.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_heartbeat_manager.rs
core/src/worker/mod.rs
sdk-core-protos/src/lib.rs
tests/integ_tests/workflow_tests/activities.rs

Core now will send cancellations if an activity would have already timed out according to server but we haven't learned of that (typically, because it isn't heartbeating). There is a configurable buffer defaulting to 5s, to avoid races with server (we would prefer to learn from server).
Nice to have your activities get cancelled when they would have been even if they don't heartbeat
1. Closes https://github.com/temporalio/features/issues/170
Unit & Integ

Local timeouts for remote activities

---

client/src/worker_registry/mod.rs
core/src/worker/client.rs
core/src/worker/client/mocks.rs
core/src/worker/mod.rs
tests/integ_tests/workflow_tests/replay.rs

This fixes issue #630 by closing the external channel early when we are using a mock client associated with the worker. 
This will disable Eager Start Workflow with mock clients, but since ESW is a latency optimization, and we do not use mock clients during its testing, this has no practical consequences.
1. Closes 
#630

Fix worker shutdown during replay test

---

README.md

* Added `Documentation` section.
* Fixed some markdown formatting.

README.md add Documentation section

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
tests/integ_tests/queries_tests.rs

Better task buffering.
To avoid timing out concurrent queries. There is no reason to buffer more than one WFT, speculative or not, for the reasons described in the second issue. We already definitely will never try to apply more than one WFT at a time if the split brain edge case mentioned there happens.
1. Closes https://github.com/temporalio/sdk-core/issues/578 and closes https://github.com/temporalio/sdk-core/issues/578
New tests

Better WFT buffer

---

sdk/src/workflow_context.rs

Updated the receiver for `WfContext::cancelled` to take in &self.
It's the only method on `WfContext` that takes `&mut self` which makes it tricky to track workflow cancellation in addition to waiting for activities to complete.

Update WfContext::cancelled to take &self instead of &mut self

---

core/Cargo.toml

We're using APIs that are [only available](https://github.com/xacrimon/dashmap/compare/v5.4.0...v5.5.0) in v5.5 (e.g. `.insert()` is used in `core/src/worker/activities.rs`). In practice, when compiling sdk-core alone, v5.5 was already what was being picked up and there was no problem. However, when sdk-core is compiled as a crate in the sdk-typescript core-bridge project, v5.4 is getting picked up, with the result that sdk-core fails to build in that context.

Fix dashmap version in Cargo.toml

---

core/src/worker/workflow/workflow_stream.rs

This never should have been a panic in the first place. I think I had it that way while testing and forgot to undo it. It's fairly hard to trigger.

Fix panic on evict w/ buffered tasks

---

core/src/replay/mod.rs

- Remove a leftover `dbg!()` statement
- @antlai-temporal's investigation identified this as probable cause of some recent failures in TS SDK's tests.

Remove a leftover dbg() statement

---

client/src/lib.rs
core/src/core_tests/activity_tasks.rs
core/src/protosext/mod.rs
core/src/telemetry/mod.rs
core/src/test_help/mod.rs
core/src/worker/mod.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/signal_external_state_machine.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/run_cache.rs
core/src/worker/workflow/workflow_stream.rs
core/src/worker/workflow/workflow_stream/saved_wf_inputs.rs
sdk-core-protos/src/history_info.rs
sdk-core-protos/src/lib.rs
sdk/src/workflow_future.rs
tests/integ_tests/visibility_tests.rs
tests/integ_tests/workflow_tests.rs

Made the current task build id sent on activations consistent with what I just did in Go / Java.
Part of https://github.com/temporalio/features/issues/253
1. Closes 

Make sure current task build id works with queries / caching

---

core/src/core_tests/queries.rs
core/src/worker/workflow/machines/workflow_machines.rs

Should've gone in https://github.com/temporalio/sdk-core/pull/665

Handle queries-in-same-wft case properly for build id in workflow info

---

client/src/workflow_handle/mod.rs
core/src/worker/workflow/machines/workflow_machines.rs
test-utils/src/lib.rs
tests/integ_tests/workflow_tests/patches.rs

Fixes a bug where removing a deprecated patch call could trigger nondeterminism if there is no subsequent command
Bugfix
1. Closes https://github.com/temporalio/sdk-core/issues/670

Fix deprecated patch removal when no subequent command

---

core/src/core_tests/queries.rs
core/src/test_help/mod.rs
core/src/worker/workflow/mod.rs
sdk-core-protos/src/history_info.rs
tests/integ_tests/queries_tests.rs

Made buffered queries be appropriately handled before a new "real" WFT if one is received while still handling an outstanding one.
The previous implementation banked on failing the tasks with the now "stale" queries if a new "real" WFT is received while they are buffered causing server to retry them while the client is still waiting on the query response. For whatever reason this doesn't always work. Instead, the implementation will now try to handle all buffered queries before applying the next real WFT. This potentially slows things down in very high-query-load scenarios, but that's more-or-less what Go and Java do and no one complains. Users shouldn't spam queries that hard anyway.
1. Closes https://github.com/temporalio/sdk-core/issues/672
3. Any docs updates …

Query buffering fixes

---

.github/workflows/per-pr.yml
core/src/core_tests/workflow_tasks.rs
core/src/worker/activities/activity_heartbeat_manager.rs
core/src/worker/activities/local_activities.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs

A particular test was hanging semi-consistently in CI despite being impossible to repro locally. 
I found a handful of other tests were panicking in the workflow processing thread because they did not perform orderly shutdowns. Fixing those has also fixed the hanging flake.

Fix CI test flake

---

core/src/worker/workflow/mod.rs

Add a couple of https://github.com/temporalio/rules references as error prefixes

Prefix some errors with rule identifiers

---

core/src/core_tests/local_activities.rs
core/src/worker/mod.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/machines/workflow_machines/local_acts.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs

Detect terminal commands and avoid doing anything else with LAs other than issuing cancels to outstanding ones.
Also fixed a possible shutdown hang that this surfaced.
Bugfix
1. Closes https://github.com/temporalio/sdk-core/issues/659
Added unit test which repro'd issue consistently, fixed it.

Fix possibly sending LA marker after WF Complete command

---

core/src/core_tests/activity_tasks.rs
core/src/worker/activities.rs

Make sure we flush activity completions to server before shutting down
It's nice. We already wait for outstanding activities to complete. It makes sense to make sure we actually do something with those results.
1. Closes https://github.com/temporalio/sdk-core/issues/594
Added UT

Wait for activity completes to reach server before shutdown

---

client/src/lib.rs

Retry policy attribute has been added to client `start_workflow` method to allow the Rust client to specify a retry policy when starting a workflow.
It's a useful param for some use cases and it was not available on Rust client while it is available for client of other languages (like go, typescript or python).

client: add retry policy param to start_workflow

---

core/src/telemetry/mod.rs
sdk/src/lib.rs

Removed the `Debug` constraint for `ActExitValue` and `WfExitValue` type parameters.
I ran into this while trying to convert some code to a Temporal activity, and was surprised by these constraints. They don't seem to actually be used by anything in the core SDK repo, so it seems safe to remove?
1. How was this tested: `cargo check --all-targets` still passes
2. Any docs updates needed: rustdoc should take care of this

sdk: remove unnecessary Debug constraints

---

client/src/lib.rs

Add a `_pem` suffix to both `ClientTlsConfig` fields, and remove the `client_` prefix (which is redundant with the `ClientTlsConfig` type name) to try to balance the length increase.
While trying to get a Rust SDK worker connected to Temporal Cloud, I got a `TonicTransportError(tonic::transport::Error(Transport, PrivateKeyParseError))`. This turned out to because I was passing DER-encoded private key and certificate to `ClientTlsConfig` instead of PEM. tonic's [`Identity::from_pem()`](https://docs.rs/tonic/latest/tonic/transport/struct.Identity.html#method.from_pem) makes it obvious that they should be PEM, but that context isn't obvious when looking at the rustdoc for `temporal_client::ClientTlsConfig` (and in fact, because it uses a `Vec<u8>` type instead of a `String` type, it suggests …

client: clarify encoding of ClientTlsConfig field data

---

Cargo.toml
core-api/Cargo.toml
core/Cargo.toml
fsm/rustfsm_procmacro/Cargo.toml
sdk-core-protos/Cargo.toml
sdk/Cargo.toml

Changed the derive_more dependency to specify `default-features = "false"` plus a minimal set of derives that are actually used.
Helps minimize transitive dependencies brought in by derive_more.
1. Closes: related to #687
2. How was this tested: it still compiles
3. Any docs updates needed: no

Use fine-grained features for derive_more

---

core/src/worker/workflow/machines/workflow_machines.rs
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/event_type.proto
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/reset.proto
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/update.proto
sdk-core-protos/protos/api_upstream/temporal/api/history/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/workflowservice/v1/request_response.proto
sdk-core-protos/src/lib.rs

Update sdk-core to work with the new `EVENT_TYPE_WORKFLOW_EXECUTION_UPDATE_REQUESTED` event added in https://github.com/temporalio/api/pull/351
I have built `sdk-python` against this branch and have an in-progress server branch that demonstrates correct processing of the new update event by `sdk-python`: https://github.com/temporalio/temporal/pull/5361

Updates for update reapply 

---

Cargo.toml
client/Cargo.toml
core/Cargo.toml
core/src/core_tests/mod.rs
core/src/worker/client/mocks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/transition_coverage.rs
sdk/Cargo.toml
test-utils/Cargo.toml
tests/integ_tests/update_tests.rs

Removed dependencies on lazy-static in favor of once_cell. Use a workspace dependency to manage the once_cell dependency in one place.
lazy-static is [effectively deprecated](https://github.com/rust-lang-nursery/lazy-static.rs/issues/214) and the ecosystem has largely moved over to once_cell. once_cell has a more ergonomic API.
1. How was this tested: still compiles
2. Any docs updates needed: don't think so?

Remove lazy-static in favor of once_cell

---

client/src/lib.rs

* Increase backoff factor to 1.7 (from 1.5) for non-poll RPCs
The current backoff factor causes clients using the Core SDK to exhaust their retries within 6.011 to 8.966 seconds, depending on random jitter.  We want to ensure that all clients keep retrying for at least 10 seconds.  With the new backoff factor, retries will not be exhausted until 11.878 to 17.767 seconds after the initial failure.
This advances progress on https://github.com/temporalio/features/issues/27 (aka SDK-118 in internal Jira).

Slow down retries so we keep retrying for more than 10 seconds.

---

client/Cargo.toml
core-api/Cargo.toml
core/Cargo.toml
core/src/telemetry/metrics.rs
core/src/telemetry/mod.rs
core/src/telemetry/otel.rs
sdk/Cargo.toml

Make the telemetry features optional but enabled by default in the core SDK.
This is a first take -- happy to take feedback and iterate.
As discussed in #687, it would be nice to limit dependencies. When using the Rust SDK, the application might have its own tracing subscriber setup, and it would be better for the libraries not to interfere with that.
1. See #687
2. How was this tested: it still compiles
3. Any docs updates needed: not sure?

core: make opentelemetry dependencies optional

---

client/src/lib.rs
client/src/raw.rs
core/src/ephemeral_server/mod.rs
sdk/src/lib.rs
test-utils/src/histfetch.rs
test-utils/src/lib.rs
tests/integ_tests/client_tests.rs
tests/integ_tests/ephemeral_server_tests.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/visibility_tests.rs
tests/integ_tests/workflow_tests/eager.rs
tests/main.rs

* Move `headers` from `connect` to the `ClientOptions` (💥 - intentional compatibility break)
* Add `api_key` to `ClientOptions` and `set_api_key` on client to use as an "Authorization" bearer header if that header not already set
1. Closes #695

Explicit API key option on client

---

client/src/metrics.rs
core-api/src/telemetry.rs
core-api/src/telemetry/metrics.rs
core/src/telemetry/metrics.rs
core/src/telemetry/otel.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/workflow_tests.rs

Support floating-point histograms to allow emitting metrics in seconds.
:boom:  Breaking changes for lang :boom: 
* The `CoreMeter` interface has changed to support `f64` histograms/gauges and `Duration`-accepting histograms
* `CoreMeter` implementations determine what units are emitted by a `HistogramDuration`
* The `unit` field on the parameter is expected to be overridden by such impls
* Correspondingly, the `MetricEvent`s used with the buffer for lang-side metrics impls have new variants
Some people desire seconds-based latencies. Also will work OOTB with our dashboards for other langs
1. Closes https://github.com/temporalio/sdk-core/issues/554
Added tests

Allow emitting duration metrics in seconds

---

client/Cargo.toml
client/src/lib.rs
client/src/proxy.rs

* Added new `client::proxy` module for HTTP CONNECT support
* Hyper/Tonic don't support this natively, so some workarounds had to be done
* Based on user need, this also includes authentication
* Added new `http_connect_proxy` client option
Can't really perform a test of this without a more involved integration test that has a full proxy server implementation. I have manually tested this with Python SDK using this version of core and connecting to Temporal cloud through the proxy. Now that proxies are officially supported by Temporal, there's a feature PR at https://github.com/temporalio/features/pull/447 for testing them, and Python will be added once this is merged and the Python SDK is updated
1. Closes #309

HTTP CONNECT proxy support

---

core/Cargo.toml
core/src/ephemeral_server/mod.rs

- Removed the special handling of "ephemeral server kill" that had been introduced a long time ago to resolve the creation of zombie process on Python 3.7.
- It appears that this special kill handling was causing high number of CI flakes in TS SDK, and the special handling seems to no longer be required in Python, since we dropped support for Python 3.7, and 3.8+ doesn't reproduce the bug.

Remove Python 3.7's special ephemeral server kill

---

client/src/worker_registry/mod.rs
core/src/worker/mod.rs

Based on comment at https://github.com/temporalio/sdk-core/pull/721#discussion_r1575409008, I have basically changed the approach that PR took where it stored slot provider on the worker, and just put it back the way it was, but also returned the slot provider from the `unregister` call so it could be used again for the next `register` call.

Do not hold eager workflow slot provider on worker

---

client/src/lib.rs
client/src/workflow_handle/mod.rs

As discussed in Slack, there is a basic API for awaiting workflow results from a client. Unfortunately the `GetWorkflowResultOpts` type that must be passed into `get_workflow_result()` is not exported, so this function cannot be called by SDK users.
I have a use case for awaiting the result of a workflow execution.
1. Closes: no issue
2. How was this tested: untested for now
3. Any docs updates needed: added some docstrings to newly public methods

client: allow public access to WorkflowHandle

---

core/Cargo.toml
core/src/ephemeral_server/mod.rs
tests/integ_tests/ephemeral_server_tests.rs

* Remove Temporalite as an ephemeral server option
* Expose child process ID for ephemeral servers
* Add assertion for CLI dev server that process is gone after shutdown
Done as part of https://github.com/temporalio/features/issues/470
1. Closes #731

Remove temporalite ephemeral server and expose child process ID

---

client/Cargo.toml
client/src/lib.rs
client/src/metrics.rs
core/Cargo.toml
core/src/ephemeral_server/mod.rs
core/src/telemetry/log_export.rs
tests/integ_tests/metrics_tests.rs

The request failure metrics weren't actually being incremented when they should've been due to the interceptor only caring about http errors and not inspecting grpc statuses. That is fixed, and error code labels are attached w/ an option to disable.
Part of https://github.com/temporalio/features/issues/144
1. Closes 
Added IT

Fix request failure metric & add error code labels

---

core-api/src/errors.rs
core/src/core_tests/workers.rs
core/src/test_help/mod.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs

Fixed a scenario where Core wouldn't properly shut itself down if it only gets poll error responses
Hang on shutdown bad
1. Closes https://github.com/temporalio/sdk-core/issues/667
Added reproing unit test

Fix possible shutdown hang if pollers keep getting gRPC errors

---

core/src/core_tests/local_activities.rs
core/src/retry_logic.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
sdk/src/lib.rs
tests/fuzzy_workflow.rs
tests/integ_tests/activity_functions.rs
tests/integ_tests/update_tests.rs
tests/integ_tests/workflow_tests/activities.rs
tests/integ_tests/workflow_tests/local_activities.rs

Allow explicit configuration of next retry backoff for LAs
* Also made breaking changes to the unreleased Rust SDK to make testing this work better. Activity functions may need to call `into()` on returned errors.
Parity with normal activities
1. Closes https://github.com/temporalio/sdk-core/issues/735
Added tests

Explicit activity retry delays for local activites

---

.github/workflows/heavy.yml
.github/workflows/per-pr.yml

- Updated all GHA actions to latest.
- GitHub is pulling the plug on `upload-artifact@v3`in October;
- All GHA actions based on Node 16 are deprecated;
- actions-rs/cargo@v1 and actions-rs/toolchain@v1 are no longer maintained

Bump GitHub Actions

---

core/src/core_tests/workflow_tasks.rs
core/src/lib.rs
core/src/worker/mod.rs
core/src/worker/tuner.rs
core/src/worker/tuner/resource_based.rs
tests/heavy_tests.rs

Makes the TS PR here (& other upcoming langs) a bit simpler https://github.com/temporalio/sdk-typescript/pull/1433

Simplify the passing of tuner options from lang to core

---

core/src/telemetry/otel.rs

Changed the `otel::default_resource` function use the Resource's default trait instead of providing a single custom default attributes, which is just a fixed service name. 
This makes the OTLP Exporter respect common env vars such as `OTEL_RESOURCE_ATTRIBUTES`, [see here](https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_resource_attributes).

Use Resource::default in order to respect common OTEL env vars

---

sdk/src/workflow_context.rs

Add a `WfContext::task_queue()` member allowing the workflow code to access the task queue from which it is being run.
Would like to schedule child workflows or activities on the same task queue as the current workflow.

sdk: expose WfContext:task_queue()

---

sdk-core-protos/src/lib.rs
sdk/src/workflow_context/options.rs

Changed `ChildWorkflowOptions::task_queue` from `String` to `Option<String>`. Apparently when left empty, the task queue for child workflows is inherited from the initiating workflow. In Rust, things like this are usually expressed in the type system rather than with sentinel values -- attempt to reflect that in the SDK interface here.
Makes it more obvious that the task queue can be inherited from the initiating activity.

sdk: make ChildWorkflowOptions::task_queue an Option

---

client/src/lib.rs
client/src/raw.rs
core/Cargo.toml
core/src/abstractions.rs
core/src/core_tests/workflow_tasks.rs
core/src/pollers/poll_buffer.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
tests/integ_tests/client_tests.rs

Added tests for grpc-timeout header (which was already working properly turns out)
Made certain rpcs that do/can act like long-polls use the long poll timeout.
One unrelated bit of cleanup around slot permit reservation I had pending.
Better timeouts
1. Closes https://github.com/temporalio/sdk-core/issues/774
Added tests

Ensure some rpcs use long-poll timeout

---

core/src/core_tests/determinism.rs
core/src/core_tests/workflow_tasks.rs
core/src/internal_flags.rs
core/src/test_help/mod.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
sdk-core-protos/src/history_builder.rs

Fixes #778 
- Previously, core was truncating commands received from lang at the first terminal command.
- With this PR, if there are terminal commands, we remove them all and replace the first one at the end of the command sequence.
- unit tests added for new and old logic
- TODO: add tests of replay / flag logic to `core`
- https://github.com/temporalio/sdk-python/pull/569 uses these changes and contains tests demonstrating that update completions are now honored, even when after workflow completion.

Honor all non-terminal commands

---

client/src/lib.rs
client/src/raw.rs
core/Cargo.toml
tests/integ_tests/client_tests.rs

#780 caused the `sdk-python` test `tests/worker/test_workflow.py::test_workflow_update_timeout_or_cancel` to fail, because the grpc-timeout header set here was not honored:
https://github.com/temporalio/sdk-python/blob/c4b1a019ad2627edb20a954edfd57c9ba414f3d5/tests/worker/test_workflow.py#L4482
https://github.com/temporalio/sdk-python/blob/c4b1a019ad2627edb20a954edfd57c9ba414f3d5/tests/worker/test_workflow.py#L4523 
@Sushisource defer to you on the correct resolution. FWIW, this PR makes the test pass again.

Don't overwrite grpc-timeout header on update requests

---

Cargo.toml
client/Cargo.toml
client/src/metrics.rs
client/src/proxy.rs
client/src/raw.rs
client/src/retry.rs
core/Cargo.toml
core/src/protosext/mod.rs
core/src/retry_logic.rs
core/src/telemetry/otel.rs
core/src/worker/activities.rs
core/src/worker/client/mocks.rs
core/src/worker/mod.rs
core/src/worker/workflow/driven_workflow.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/timer_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/machines/workflow_task_state_machine.rs
core/src/worker/workflow/workflow_stream.rs
sdk-core-protos/Cargo.toml
sdk-core-protos/src/history_builder.rs
sdk/Cargo.toml
sdk/src/activity_context.rs
sdk/src/workflow_context.rs
test-utils/src/canned_histories.rs
tests/integ_tests/client_tests.rs

Upgrade Tonic, Prost, OTel deps
Updated dependencies
tonic - 0.12.x
prost - 0.13.x
otel - 0.24.x
To upgrade to hyper 1.x ecosystem
1. Closes [#626](https://github.com/temporalio/sdk-core/issues/626)
```
cargo test
cargo integ-test
```
To avoid mixing changes (Rust 1.80 clippy throwing lints)
```
cargo clippy --all -- -D warnings -A clippy::clone-on-copy
```
NA

Upgrade tonic, prost, otel to latest

---

sdk/src/lib.rs

This changes the check to warn about the workflow and allows the worker to continue polling from the queue similar to the other SDKs.
Currently, there is no good way of writing a test to make sure this isn't introduced by a refactor in the future.
Maybe with a custom tracing subscriber to check for the warn output, but that would be something for it's own PR.
Previously, the worker would panic due to the error return value of the activation handler.
Other SDKs do not panic/exit upon an unknown workflow. 
1. Closes #558
Start an empty worker with a local dev instance and start a workflow with any name. The worker should not exit.
Not really.

rust-sdk: prevent panic on non-existing workflow

---

client/src/lib.rs
tests/integ_tests/client_tests.rs

TLS connections to the Cloud Ops API (which does not use mTLS like other connections) were failing with unknown CA problems.

Make sure to use native roots / add cloud ops API test

---

core/src/worker/workflow/machines/activity_state_machine.rs
tests/integ_tests/workflow_tests/activities.rs

Abandon mode activities getting cancelled before being started were not waking up lang
Bug
1. Closes 

Fix cancel-before-start abandon activities

---

core/src/core_tests/queries.rs
sdk-core-protos/src/lib.rs
sdk/src/lib.rs
sdk/src/workflow_future.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/queries_tests.rs
tests/integ_tests/worker_tests.rs
tests/integ_tests/workflow_tests.rs

This makes sure unknown workflows are handled on-par with other SDKs. This is done by emitting a `WorkflowActivationComplete` message with state set to failure.
This is based on feedback from https://github.com/temporalio/sdk-core/pull/784
The recent changed avoided panics caused by unknown workflows. The workflow activation was never marked as failed.
This made it hard to add a test for this behavior.
Test is added to check for the correct behavior.

Rust-SDK: Handle unknown workflow

---

core/src/core_tests/queries.rs
core/src/worker/workflow/managed_run.rs
tests/integ_tests/queries_tests.rs

Do not send queries if the task would be failed anyway
Pointless waste of time and effort, and can potentially un-fail the WFT if a legacy query is successfully responded to.
1. Closes https://github.com/temporalio/sdk-core/issues/786
Added test

Do not send queries after we would fail WFT

---

core/src/worker/workflow/driven_workflow.rs
core/src/worker/workflow/machines/workflow_machines.rs
sdk/src/workflow_context.rs
sdk/src/workflow_future.rs
tests/integ_tests/workflow_tests/upsert_search_attrs.rs

Previously we only CAN'd with the initial SAs. This makes us consistent with (at least Go, tbd Java) where we also include updates made during the workflow, which just makes sense.
Sensible. Parity.
1. Closes https://github.com/temporalio/sdk-core/issues/791
Updated integ test

Include SA updates made in-workflow when continuing as new

---

core/src/core_tests/activity_tasks.rs
core/src/core_tests/local_activities.rs
core/src/core_tests/queries.rs
core/src/core_tests/updates.rs
core/src/core_tests/workflow_cancels.rs
core/src/core_tests/workflow_tasks.rs
core/src/ephemeral_server/mod.rs
core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/cancel_workflow_state_machine.rs
core/src/worker/workflow/machines/patch_state_machine.rs
core/src/worker/workflow/mod.rs
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/lib.rs
sdk/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_future.rs
test-utils/src/lib.rs
tests/integ_tests/queries_tests.rs
tests/integ_tests/update_tests.rs
tests/integ_tests/visibility_tests.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/resets.rs
tests/integ_tests/workflow_tests/upsert_search_attrs.rs
tests/runner.rs

Make `UpdateRandomSeed` jobs come after start workflow, but before everything else.
These could technically have consequences for later actions, and should go first. It's intuitive.
The more delicate change here is actually sorting `StartWorkflow` before other stuff, which also seems intuitive, but a number of tests at least in core had some expectations around updates being able to come first. Frankly, that doesn't make a ton of sense, and I don't really expect this move to be any kind of real issue, but it might require some changes to langs that are using `StartWorkflow` as a synonym for "do first iteration of the event loop"? If such changes are needed, they should be the ones described here: https://github.com/temporalio/sdk-python/issues/606 (.NET may need an equivalent item) as …

Job ordering updates

---

core-api/src/telemetry.rs
core/Cargo.toml
core/src/telemetry/mod.rs
core/src/telemetry/otel.rs
docker/docker-compose-telem.yaml
etc/otel-collector-config.yaml
test-utils/src/lib.rs
tests/integ_tests/metrics_tests.rs

Add proper (newly needed) TLS config to OTel exporter
Needed for anyone with external collectors, like datadog etc.
1. Closes https://github.com/temporalio/sdk-core/issues/801
Added a test (which needs to be run manually right now, will add to CI later)

Make sure OTel exporter can work properly with TLS

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_task_poller_stream.rs
core/src/worker/mod.rs
core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/mod.rs
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/lib.rs
sdk/src/workflow_future.rs
tests/integ_tests/heartbeat_tests.rs
tests/integ_tests/workflow_tests/activities.rs
tests/integ_tests/workflow_tests/local_activities.rs

Always resolve LAs last within one activation
I am confident this does not need a flag for the reasons explained in the docstring for the test. If you were in this situation before, you were experiencing UB that would likely lead to an NDE. The only situation this change impacts _is_ exactly that situation. The test docstring explains why you can't force something else to happen.
However, we should still test this change in lang SDKs with the fuzzer before releasing them with it.
Well explained by docstrings
1. Closes https://github.com/temporalio/sdk-core/issues/803
Added reproing test

Fix possible NDEs caused by LAs & immediate cancels resolving in different order upon replay

---

core/src/core_tests/queries.rs
core/src/worker/workflow/managed_run.rs

Make sure we still reply to legacy queries in specific failure scenarios
Could cause timeouts where they were not necessary
1. Closes 
Existing tests

Fix legacy query failure replying

---

client/Cargo.toml
client/src/lib.rs
client/src/raw.rs
client/src/retry.rs
client/src/workflow_handle/mod.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
tests/integ_tests/workflow_tests/activities.rs

* Fixed get workflow history not being considered a long-poll call (discovered while trying to repro)
* Retry at most once the specific error users have seen occasionally during activity completions
Avoid spurious rpc failures due to goaways
1. Closes https://github.com/temporalio/sdk-core/issues/807
Could not repro the exact case, but, by analysis this should allow that situation to retry at most once.

Attempt to address unusal rpc cancellation error

---

client/src/raw.rs
client/src/retry.rs
tests/integ_tests/client_tests.rs

Differentiated user-initiated long polls from task long polls to continue respecting timeouts in those cases
We don't want to ignore a gRPC timeout for a user made call
1. Closes 
Upgraded test

Respect gRPC timeouts on get wf execution history

---

sdk-core-protos/src/lib.rs

I added a helper function to `ActivityResolution` to cover a use case of mine that may also help others (the idea to do this emerged from a discussion in the **sdk-core** Slack channel).
I've been using this lib to create my own makeshift SDK and wanted a kind of quick-and-dirty way to extract the payload from an activity, but without any use of `unwrap()` (making `unwrap_ok_payload` a bit too "unsafe" for my liking). I have my own function along these lines but wanted to contribute it upstream.
1. Closes **N/A** (it's a small enough change that I opted not to create an issue).
2. How was this tested: no tests necessary beyond compilation
3. Any docs updates needed? I don't believe so

Add helper function for extracting success payload

---

core/src/ephemeral_server/mod.rs
core/src/telemetry/metrics.rs
core/src/worker/activities.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
tests/integ_tests/metrics_tests.rs

Added local activity metrics to core. No flag needed as these were not being recorded under existing activity metrics anyway.
Parity with other SDKs
1. Closes https://github.com/temporalio/features/issues/522
Added integ test against Prometheus metrics
Yes, docs site needs tables etc on metrics page updated

La metrics

---

core/src/ephemeral_server/mod.rs

CLI can overflow UI port (should fix this there too). Avoid that.
Big port bad
1. Closes https://github.com/temporalio/sdk-core/issues/767

Avoid CLI overflowing UI port

---

sdk-core-protos/protos/local/temporal/sdk/core/activity_result/activity_result.proto
sdk-core-protos/protos/local/temporal/sdk/core/activity_task/activity_task.proto
sdk-core-protos/protos/local/temporal/sdk/core/child_workflow/child_workflow.proto
sdk-core-protos/protos/local/temporal/sdk/core/common/common.proto
sdk-core-protos/protos/local/temporal/sdk/core/core_interface.proto
sdk-core-protos/protos/local/temporal/sdk/core/external_data/external_data.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_completion/workflow_completion.proto

Need `Temporalio::Bridge::Api` to be `Temporalio::Internal::Bridge::Api`

Add "Internal" to Ruby package for Core protos

---

core/Cargo.toml
sdk-core-protos/build.rs

Use the system-native TLS CAs instead of rustls's built-in CAs

---

sdk/Cargo.toml
sdk/src/workflow_context.rs
sdk/src/workflow_future.rs

Replaced `crossbeam-channel` crate with `std::sync::mpsc`
Noticed that `crossbeam-channel` is being used unnecessarily.
Run `cargo test`

Use mpsc instead crossbeam-channel

---

.github/workflows/per-pr.yml
Cargo.toml
client/Cargo.toml
client/src/lib.rs
core/Cargo.toml
core/src/abstractions/take_cell.rs
core/src/core_tests/mod.rs
core/src/replay/mod.rs
core/src/telemetry/otel.rs
core/src/worker/client/mocks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/transition_coverage.rs
test-utils/Cargo.toml
test-utils/src/lib.rs
tests/integ_tests/update_tests.rs

Replaced `once_cell` with `std::sync`
Since you can already directly use `OnceLock` and `LazyLock` from std without an additional crate. However, this would require raising MSVR to 1.80 because of `LazyLock`, but `OnceLock` can be used from 1.70 onwards.
Considering that the current approximate MSVR is `1.77` (based on GitHub Workflow) I think it won't be a big deal to raise it to `1.80`.
Run `cargo test`

Replace once_cell with std::sync::{OnceLock,LazyLock}

---

sdk-core-protos/Cargo.toml
sdk-core-protos/build.rs
sdk-core-protos/src/lib.rs

Spencer previously implemented a pretty-print for `Display` for `Payload`. `Debug` was not touched because prost automatically generated the `Debug` impl for `Payload`. Prost and tonic-build now support skipping the `Debug` impl, https://github.com/tokio-rs/prost/pull/797, so we can leverage this to provide our own `Debug` impl.
Also added support to skip this truncation by specifying the `TEMPORAL_PRINT_FULL_PAYLOADS` env variable
A nice-to-have feature to make debug logs more readable.
1. Closes 
#806
Generated temporal.api.common.v1.rs now generates 
```
#[cfg_attr(
feature = "serde_serialize",
derive(::serde::Serialize, ::serde::Deserialize)
)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
#[prost(skip_debug)]
pub …
```

Move Payload pretty-print from Display to Debug

---

core/Cargo.toml
core/src/worker/tuner/resource_based.rs

Factor in cgroup memory limits to resource based tuner.
The crate doesn't have support at the moment for CPU limits. I tried to parse it semi-manually like we did in the Go SDK, but even then I don't have the right metric (elapsed cpu microseconds) to make the calculation - and even then, setting CPU limits is an [ill-advised thing to do anyway](https://home.robusta.dev/blog/stop-using-cpu-limits?nocache=234) so missing this feature is unlikely to bother anyone.
Tested w/ omes

Account for cgroup memory limits

---

core/src/core_tests/updates.rs
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/workflow_machines.rs
sdk/src/workflow_context.rs
sdk/src/workflow_future.rs
tests/integ_tests/update_tests.rs

Fixed a bug where an empty WFT sequence followed by an update could cause the update job to be sent before things that happened preceding the empty sequence.
Bugfix
1. Closes https://github.com/temporalio/sdk-python/issues/673
UT / IT

Fix possible replay bug with empty WFT sequences and updates

---

core-api/src/worker.rs
core/src/abstractions.rs
core/src/core_tests/workflow_tasks.rs
core/src/pollers/poll_buffer.rs
core/src/worker/activities.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
core/src/worker/slot_provider.rs
core/src/worker/tuner/fixed_size.rs
core/src/worker/tuner/resource_based.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_extraction.rs
tests/integ_tests/worker_tests.rs

Make sure the resource tuner is always willing to hand out a minimum of 1 slot for sticky and non-sticky WFT polls
Avoids a scenario where the sticky pollers can hog all the slots, starving normal poller.
1. Closes https://github.com/temporalio/sdk-core/issues/775
Added IT

Ensure resource tuner won't get WFTs stuck

---

core/src/abstractions.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs

Needed for custom slot supplier work

Ensure all permits are released before shutdown resolves

---

core/src/core_tests/activity_tasks.rs
core/src/core_tests/child_workflows.rs
core/src/core_tests/updates.rs
core/src/core_tests/workers.rs
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/child_workflow_state_machine.rs
core/src/worker/workflow/machines/timer_state_machine.rs
sdk-core-protos/protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
sdk/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_context/options.rs
test-utils/src/lib.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/queries_tests.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/activities.rs
tests/integ_tests/workflow_tests/replay.rs
tests/integ_tests/workflow_tests/timers.rs

added `static_summary` and `static_details` to  child workflow
added `summary` to timer and activity
and plumbed all new fields to user_metadata in command sent to server. 
This allows individual SDK languages to pass this information to the server, allowing it to show up in the UI.
1. Closes #830
Wrote new tests to validate metadata is being passed to server

Support user metadata in child workflow, timer, and activity

---

core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/workflow_stream.rs
tests/integ_tests/workflow_tests.rs

The option to fail workflows when nondeterminism errors happen automatically did not work in all circumstances, this fixes that.
Bug
1. Closes https://github.com/temporalio/sdk-core/issues/855
Added test

History ooo bug

---

client/src/lib.rs
client/src/workflow_handle/mod.rs
core/Cargo.toml
core/src/worker/workflow/machines/cancel_nexus_op_state_machine.rs
core/src/worker/workflow/machines/mod.rs
core/src/worker/workflow/machines/nexus_operation_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
sdk-core-protos/protos/local/temporal/sdk/core/nexus/nexus.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
sdk-core-protos/src/lib.rs
sdk/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_context/options.rs
sdk/src/workflow_future.rs
test-utils/src/lib.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/nexus.rs
tests/runner.rs

> [!NOTE]
> Note that this isn't going into main, but a nexus branch 
Add ability for langs to perform nexus operations from workflows
Nexus is cool yo
1. Closes 
Added integration tests

Nexus WF Machines & Lang Support

---

core/src/ephemeral_server/mod.rs

This is a relatively simple fix: the ephemeral server code isn't using the correct option name for setting the SQLite filename argument.
I didn't check old versions of the ephemeral server, but I am at least confident that for `temporal version 1.0.0 (Server 1.24.2, UI 2.28.0)`, the current flag is incorrect.
1. Closes 
Ran the updated SDK against our internal codebase and validated that the flag worked. I can add a regression test if y'all like, but wasn't sure if it was worth it here.

Fix DB filename argument for ephemeral server

---

.gitignore
core/src/core_tests/workers.rs
core/src/internal_flags.rs
core/src/worker/client.rs
core/src/worker/client/mocks.rs
core/src/worker/mod.rs
core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/child_workflow_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/run_cache.rs
core/src/worker/workflow/workflow_stream.rs

Title. Automatically derived from client settings, no lang-visible change needed.
Parity, useful for investigations
1. Closes https://github.com/temporalio/sdk-core/issues/588

Write sdk name & version to WFT completes

---

client/Cargo.toml
client/src/lib.rs
client/src/metrics.rs
client/src/raw.rs
client/src/retry.rs
client/src/worker_registry/mod.rs
core/src/lib.rs
core/src/worker/client.rs
test-utils/src/lib.rs
tests/integ_tests/client_tests.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/update_tests.rs
tests/main.rs
tests/runner.rs

Some client cleanup I needed to do while working on poller scaling
Paying down some debt & better organization
1. Closes 
Existing tests

Client refactoring

---

.github/workflows/per-pr.yml
tests/integ_tests/ephemeral_server_tests.rs
tests/integ_tests/metrics_tests.rs

Why not
1. Closes https://github.com/temporalio/sdk-core/issues/710
bruh

Run CI on all platforms

---

core/src/core_tests/child_workflows.rs
core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/cancel_external_state_machine.rs
core/src/worker/workflow/machines/cancel_workflow_state_machine.rs
core/src/worker/workflow/machines/child_workflow_state_machine.rs
core/src/worker/workflow/machines/complete_workflow_state_machine.rs
core/src/worker/workflow/machines/continue_as_new_workflow_state_machine.rs
core/src/worker/workflow/machines/fail_workflow_state_machine.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/mod.rs
core/src/worker/workflow/machines/modify_workflow_properties_state_machine.rs
core/src/worker/workflow/machines/nexus_operation_state_machine.rs
core/src/worker/workflow/machines/patch_state_machine.rs
core/src/worker/workflow/machines/signal_external_state_machine.rs
core/src/worker/workflow/machines/timer_state_machine.rs
core/src/worker/workflow/machines/update_state_machine.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/machines/workflow_task_state_machine.rs
core/src/worker/workflow/mod.rs
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
sdk-core-protos/src/lib.rs
sdk/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_future.rs
tests/integ_tests/workflow_tests/cancel_external.rs
tests/integ_tests/workflow_tests/cancel_wf.rs
tests/integ_tests/workflow_tests/child_workflows.rs

Expose cancellation cause from user requests
1. Closes https://github.com/temporalio/sdk-core/issues/708
Upgraded integ test

Expose workflow cancel cause

---

core/Cargo.toml
test-utils/Cargo.toml

Disable the `tracing-log` feature for `tracing-subscriber` by turning off [default features](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/Cargo.toml#L27). The `ansi` feature was explicitly listed because it's used in the code.
I am trying to use `core` crate from Temporal SDK in a Rust application that already uses `tracing-subscriber`. However, it fails to initialize the subscriber because `core` depends on `tracing-subscriber` with `tracing-log` feature enabled. This behavior is documented [here](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/util/trait.SubscriberInitExt.html#method.try_init):
> This method panics if a global default subscriber has already been set, or if a log logger has already been set (when the “tracing-log” feature is enabled). …

disable tracing-log feature for tracing-subscriber

---

client/src/lib.rs
core/src/worker/activities/local_activities.rs
sdk-core-protos/protos/local/temporal/sdk/core/activity_task/activity_task.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/lib.rs
sdk/src/activity_context.rs
sdk/src/workflow_context/options.rs
tests/integ_tests/workflow_tests/priority.rs

Attach priority to core tasks

---

core-api/src/worker.rs
core/src/core_tests/queries.rs
core/src/core_tests/workflow_tasks.rs
core/src/lib.rs
core/src/test_help/mod.rs
core/src/worker/client.rs
core/src/worker/mod.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/protos/local/temporal/sdk/core/workflow_completion/workflow_completion.proto
sdk-core-protos/src/lib.rs
sdk/src/lib.rs
sdk/src/workflow_future.rs
test-utils/src/lib.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/update_tests.rs
tests/integ_tests/worker_tests.rs
tests/integ_tests/worker_versioning_tests.rs
tests/integ_tests/workflow_tests.rs
tests/main.rs
tests/runner.rs

Added necessary bits to enable worker deployment based versioning
> [!NOTE]
> Breaking change for lang implementers: I shuffled around the build id and legacy versioning stuff to make it compile-time mutually exclusive with this new stuff. 
Feature train choo choo :bullettrain_side: 
1. Closes https://github.com/temporalio/sdk-core/issues/889
Added fairly straightforward integ test. The testing in core isn't so valuable except to ensure the right stuff is sent to server, which is largely true for lang as well.

Worker Deployment Versioning

---

core/src/worker/client.rs
test-utils/src/lib.rs
tests/integ_tests/worker_versioning_tests.rs

Realized I missed a few spots while going through the Python impl

Attach deployment options in a few missing spots

---

core-api/src/worker.rs
core/src/abstractions.rs
core/src/worker/mod.rs

Include deployment version on slot reservation context

---

client/src/raw.rs
core/src/telemetry/metrics.rs
core/src/worker/activities.rs
core/src/worker/activities/local_activities.rs
core/src/worker/workflow/managed_run.rs
sdk-core-protos/protos/api_upstream/openapi/openapiv2.json
sdk-core-protos/protos/api_upstream/openapi/openapiv3.yaml
sdk-core-protos/protos/api_upstream/temporal/api/batch/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/common.proto
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/event_type.proto
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/workflow.proto
sdk-core-protos/protos/api_upstream/temporal/api/failure/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/history/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/rules/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/workflow/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/workflowservice/v1/request_response.proto
sdk-core-protos/protos/api_upstream/temporal/api/workflowservice/v1/service.proto
sdk-core-protos/src/lib.rs

Updated temporal api to get application error category, use the category to filter out benign application failures from failure metrics.
Part of benign exceptions work
Closes #897

Handle metrics for benign application failures

---

core/src/core_tests/activity_tasks.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_heartbeat_manager.rs
core/src/worker/activities/local_activities.rs
sdk-core-protos/protos/local/temporal/sdk/core/activity_task/activity_task.proto
sdk-core-protos/src/lib.rs

Add `Pause` as a reason for activity cancellations.
Provide visibility to consuming lang-SDKs to discern whether the activity has been paused.
Note that if both the cancellation and activity flags are set, the activity will be *cancelled*, **not** paused. This follows the same priority as Java.
1. Closes #895
Unit test
Nope

Activity pause interrupt heartbeat

---

core-api/src/telemetry/metrics.rs
core-api/src/worker.rs
core/src/abstractions.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
core/src/worker/tuner.rs
core/src/worker/tuner/resource_based.rs
tests/integ_tests/metrics_tests.rs

Add metrics meters to slot supplier contexts & fix bug where attach metrics was useless on a tuner holder
Fixes bug & allows for recording metrics on slot supplier contexts.
Mostly used this as a testpiece for some agentic AI coding.
1. Closes https://github.com/temporalio/sdk-core/issues/904
Added test

Add meters to custom slot supplier contexts

---

sdk-core-protos/protos/api_upstream/temporal/api/history/v1/message.proto

**What changed?**
- Fix a double semicolon introduced in temporalio/api#579.
**Why?**
- The double semicolon sequence is causing a compilation error in `protobufjs`, even though this is technically valid according to [the official Protobuf 3 spec](https://protobuf.dev/reference/protobuf/proto3-spec/#emptystatement).
This is a bug in `protobufjs`, for which there's been [an open issue ticket](https://github.com/protobufjs/protobuf.js/issues/1322) since 2019, but it was never acknowledged, and a PR fixing this has been ignored for more than a year.
Given that there's simply no reason to use a double semicolon sequence anyway, it appears preferable to simply avoid that in our proto definitions.
- This was fixed upstream in temporalio/api#589, but this is a temporary, targeted-fix to avoid …

Fix protobuf syntax that is causing an error in protobufjs

---

.cargo/config.toml
.github/workflows/per-pr.yml
client/src/lib.rs
client/src/retry.rs
core/Cargo.toml
core/src/worker/workflow/mod.rs
test-utils/src/lib.rs
tests/cloud_tests.rs
tests/integ_tests/worker_tests.rs
tests/main.rs

Don't retry on grpc message too large errors. Forward the error and fail the workflow task
Retries will not succeed, as they don't change the size of the message
1. Closes #462 
New worker tests

Don't retry on grpc message too large errors

---

.github/workflows/per-pr.yml
core/src/lib.rs
core/src/worker/client.rs
core/src/worker/mod.rs

Fixes https://github.com/temporalio/sdk-core/issues/883
The `WorkerClient` trait encapsulates all the methods that the worker needs to make the underlying API calls. Currently, it is only exposed to the crate. However, it is useful to expose this publicly to allow other language clients to provide their native `WorkerClient` implementation e.g. by backing it with the language specific gRPC library.
This PR makes the `WorkerClient` trait and other types public.
Other language SDKs can now substitute in their gRPC client.

Expose the `WorkerClient` trait

---

core-api/src/worker.rs
core/src/abstractions.rs
core/src/pollers/poll_buffer.rs
core/src/worker/mod.rs
core/src/worker/workflow/wft_poller.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/polling_tests.rs
tests/integ_tests/workflow_tests.rs

Fixes an issue that could cause task timeouts when using very small (<2) numbers of WFT slots or pollers.

Fix bad balacing between sticky & nonsticky WFT polling with low slot/poller counts

---

core/src/ephemeral_server/mod.rs

Quality of life
1. Closes https://github.com/temporalio/sdk-core/issues/935

Print the last error when failing to connect to ephemeral server

---

.github/workflows/per-pr.yml
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/wft_poller.rs

Fix a bug that prevented `PollWorkflowTaskQueue` to the sticky task queue if `workflow_task_poller_behavior = PollerBehavior::SimpleMaximum(2)`. This was resulting in slower performance, and would cause "sticky worker unavailable, please use original task queue." error messages on the server.

Fix wft poll balancing with maxpoll=2

---

core/src/pollers/poll_buffer.rs

Avoid chopping down pollers if they can't ever be scaled back up

Don't scale down on errors w/ poller autoscale unlesss seen a decision

---

core/src/worker/workflow/machines/nexus_operation_state_machine.rs
sdk-core-protos/protos/local/temporal/sdk/core/nexus/nexus.proto

WAIT_CANCELLATION_COMPLETED should be default, populate operation_token on cancellation failures
Default should have the same behavior as before the expansion of cancellation types.
1. Closes 
Tested the change in the python SDK

Nexus cancellation type fixes

---

AGENTS.md
core/src/core_tests/workflow_tasks.rs
core/src/ephemeral_server/mod.rs
core/src/test_help/mod.rs
core/src/worker/workflow/mod.rs
sdk/src/lib.rs
sdk/src/workflow_future.rs

Fixes a handful of test flakes
Closes https://github.com/temporalio/sdk-core/issues/752

Fix flaky tests

---

core-c-bridge/src/worker.rs
core/src/telemetry/mod.rs

Possibly prevents encountering the tracing bug with panic on span drop, and is just generally sensible anyway.

Use guard instead of default for thread in enter_sync!

---

client/src/raw.rs
core-api/src/envconfig.rs
core-api/src/worker.rs
core-c-bridge/build.rs
core-c-bridge/src/runtime.rs
core-c-bridge/src/tests/context.rs
core/src/test_help/mod.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
tests/integ_tests/queries_tests.rs
tests/integ_tests/workflow_tests/local_activities.rs

Fixed compiler warnings and lints added in Rust 1.89, specifically:
- Hidden lifetimes warning
- Flattening if-let chains
- Using `std::slice::from_ref` to avoid cloning
Removes warnings from compiler output, and CI would start failing when we upgrade to Rust 1.89.
Ran `cargo lint` and `cargo test-lint` locally using Rust 1.89.

Fixed compiler warnings and lints added in Rust 1.89

---

core-api/src/worker.rs
core/src/lib.rs
core/src/worker/client.rs
core/src/worker/heartbeat.rs

set worker heartbeat off by default.
SDK logs are spamming due to server not supporting this yet, turn off by default until server is ready.
1. Closes 

Disable worker heartbeat off by default

---

core/src/protosext/mod.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
sdk/src/workflow_context/options.rs
tests/integ_tests/workflow_tests/local_activities.rs

User metadata is read from `ScheduleLocalActivity` core command and passed to `RECORD_MARKER` server command on local activity completion.
Feature request: https://github.com/temporalio/features/issues/637
1. Closes #960 
2. How was this tested: Added integration test `integ_tests::workflow_tests::local_activities::local_activity_with_summary`

Support user metadata in local activity

---

client/src/lib.rs
client/src/proxy.rs
test-utils/Cargo.toml
test-utils/src/http_proxy.rs
test-utils/src/lib.rs
tests/integ_tests/client_tests.rs

* Added Unix socket/stream support
* Built HTTP connect proxy utility for testing
* Previously we had relied on the proxy tests in features, but that's too divorced from the code
* Every HTTP connect proxy lib out there had dependency or other issues
1. Closes #981

Support for Unix sockets in HTTP connect proxy

---

client/src/lib.rs
core-c-bridge/src/client.rs
tests/integ_tests/client_tests.rs

This PR allows configuring [gRPC binary metadata key/values](https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md#:~:text=Applications%20define%20binary%20headers%20by%20having%20their%20names%20end%20with%20%E2%80%9C%2Dbin%E2%80%9D.%20Runtime%20libraries%20use%20this%20suffix%20to%20detect%20binary%20headers%20and%20properly%20apply%20base64%20encoding%20%26%20decoding%20as%20headers%20are%20sent%20and%20received.) (where the key ends in `-bin`) on the Temporal client struct. It's already possible for Rust users of the Temporal client struct to set per-request gRPC binary metadata key/values; this allows setting client-wide headers.
The main API changes are:
- Added: `ClientOptions.binary_headers: Option<HashMap<String, Vec<u8>>>`
- Added: …

Add support for configuring client-wide gRPC binary metadata values, validate metadata earlier

---

core-api/src/envconfig.rs

This PR removes logic that adds a default TLS config object when api key is enabled, but no TLS configuration was provided.
This makes the API semantics more clear.
Lang SDKs will now know:
- when a TLS config object is provided by core, a configuration has been explicitly specified
- when no TLS configuration was specified (will receive no object, instead of an empty object)
Lang SDKs now know with certainty when to apply default TLS configuration to the client (generally this means `tls: true` in the client config):
- when an `api_key` is provided, but no TLS config was specified

Remove logic that auto adds TLS when api key is enabled
