temporalio/sdk-core

protos/local/activity_result.proto
protos/local/activity_task.proto
protos/local/core_interface.proto
protos/local/workflow_activation.proto
protos/local/workflow_commands.proto
protos/local/workflow_completion.proto
src/lib.rs
src/machines/activity_state_machine.rs
src/machines/mod.rs
src/machines/test_help/mod.rs
src/machines/timer_state_machine.rs
src/machines/workflow_machines.rs
src/pollers/mod.rs
src/protos/mod.rs
src/protosext/history_info.rs
src/workflow/concurrency_manager.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

What was changed:
Errors simplified and better segregated for more obvious handling. Unified polling and completion APIs
Motivation & Context:
Simpler usage from lang side.
Closes issue:

Return fewer and more specific errors / API Changes

---

src/lib.rs
src/machines/activity_state_machine.rs
src/test_help/canned_histories.rs

Added tests for untested transitions and removed some unneeded code from the state machine.

Add missing tests for the Started state in activity state machine

---

src/lib.rs

Crash if we get a history with a pagination token, until we implement it
Better than silently failing to apply the whole history

Panic on histories with pagination tokens, for now.

---

src/lib.rs
src/machines/test_help/mod.rs
src/protos/mod.rs
tests/integ_tests/polling_tests.rs
tests/main.rs

New config option for max concurrent activity tasks
Otherwise workers could get immediately swamped

Allow configuring maximum concurrent activity limits

---

protos/local/activity_task.proto
src/activity/activity_heartbeat_manager.rs
src/lib.rs
src/protos/mod.rs

Cancels from heartbeats weren't being propagated back through polling
Needed to actually cancel activities

Actually send activity cancels

---

src/activity/activity_heartbeat_manager.rs

* Use select in biased mode rather than grace period
Simplification

Additional Heartbeat Manager simplifications

---

src/lib.rs

Make shutdown properly abort both types of polling if they are ongoing at the same time, and fix AT poll timeout not getting retried automatically
Closes https://github.com/temporalio/sdk-core/issues/107
Closes https://github.com/temporalio/sdk-core/issues/108 

Fix shutdown & AT long poll timeout bugs

---

build.rs
src/activity/activity_heartbeat_manager.rs
src/errors.rs
src/lib.rs
src/machines/activity_state_machine.rs
src/machines/mod.rs
src/machines/test_help/history_builder.rs
src/machines/workflow_machines.rs
src/protos/mod.rs
src/test_help/canned_histories.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

Fix problems with activity task cancellations not being sent to lang on replay

Fix AT cancel missing on replay

---

src/activity/activity_heartbeat_manager.rs
src/errors.rs
src/lib.rs

Not sure how this even can compile -- non pub type in pub interface

Export heartbeat error

---

Cargo.toml
README.md
src/activity/activity_heartbeat_manager.rs
src/core_tracing.rs
src/lib.rs
src/machines/mod.rs
src/machines/test_help/mod.rs
src/machines/workflow_machines.rs
src/pollers/mod.rs
src/protos/mod.rs
src/protosext/mod.rs
src/task_token.rs
src/workflow/mod.rs
tests/integ_tests/simple_wf_tests.rs

Added a task token type for better formatting and better clarity in the code.
Added big concurrent workflows test & corresponding test upgrades.
Reduced hugely verbose tracing output.
This would've been easier if https://github.com/danburkert/prost/issues/334 was fixed in the protobuf builder. Will be nice when it is.
Easier debugging

Task token type, concurrent workflows test, better logs

---

Cargo.toml
src/errors.rs
src/lib.rs
src/machines/test_help/history_builder.rs
src/pollers/mod.rs
src/protos/mod.rs
src/protosext/mod.rs
src/test_help/canned_histories.rs
tests/integ_tests/simple_wf_tests.rs
tests/main.rs

Fix a simple bug preventing evictions from being sent
Fix a bug where we would autocomplete WFT timeouts wrongly
Accomplished by buffering new WFTs from server if there is one outstanding so that we don't need to wait two timeout intervals to handle stale completions
After this PR I am going to refactor things to better encapsulate all the complicated WFT management stuff

Eviction and WFT timeout / stale completion fixes

---

src/workflow_tasks.rs
tests/integ_tests/workflow_tests/stickyness.rs

Removed an unnecessary redundancy
Code cleanup I discovered while getting started on queries
1. Closes 
Existing tests

Remove an extra map that is not needed in the WFT manager

---

build.rs
protos/local/workflow_commands.proto
src/core_tests/mod.rs
src/core_tests/replay_flag.rs
src/machines/activity_state_machine.rs
src/machines/continue_as_new_workflow_state_machine.rs
src/machines/mod.rs
src/machines/timer_state_machine.rs
src/machines/transition_coverage.rs
src/machines/workflow_machines.rs
src/pollers/gateway.rs
src/protos/mod.rs
src/test_help/canned_histories.rs
src/test_help/history_builder.rs
src/test_workflow_driver.rs
src/workflow_tasks.rs
test_utils/src/lib.rs
tests/integ_tests/queries_tests.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/continue_as_new.rs
tests/integ_tests/workflow_tests/stickyness.rs
tests/integ_tests/workflow_tests/timers.rs
tests/load_tests.rs

Implement continue as new machine and command
Long running workflows
1. Closes 
Added tests

Continue as new

---

Cargo.toml

Update opentelemetry deps

---

protos/local/workflow_activation.proto
protos/local/workflow_commands.proto
src/core_tests/mod.rs
src/core_tests/queries.rs
src/core_tests/workers.rs
src/core_tests/workflow_cancels.rs
src/core_tests/workflow_tasks.rs
src/machines/cancel_workflow_state_machine.rs
src/machines/mod.rs
src/machines/transition_coverage.rs
src/machines/workflow_machines.rs
src/pollers/gateway.rs
src/protos/mod.rs
src/test_help/async_workflow_driver.rs
src/test_help/canned_histories.rs
src/test_help/history_builder.rs
src/test_help/mod.rs
src/test_workflow_driver.rs
src/workflow/driven_workflow.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/cancel_wf.rs
tests/integ_tests/workflow_tests/continue_as_new.rs
tests/main.rs

Implemented workflow cancel machine & sending activation to lang
Sometimes users cancel their workflows, ya know.
1. Closes 
New tests

Implement workflow cancellations

---

src/lib.rs

Handle completion errors everywhere they can be generated
Fixes spurious errors on shutdown
1. Closes https://github.com/temporalio/sdk-core/issues/134
New tests

Handle completion errors everywhere they can happen

---

protos/local/activity_task.proto
src/activity/activity_heartbeat_manager.rs
src/activity/mod.rs
src/lib.rs
src/protos/mod.rs

Attaches reasons to activity cancels
Better debugability
1. Closes 

Add reasons to activity cancels

---

src/activity/activity_heartbeat_manager.rs
src/activity/mod.rs
src/core_tests/activity_tasks.rs
src/machines/activity_state_machine.rs
src/machines/mod.rs
src/test_help/canned_histories.rs

Fixed bug where we could double-resolve already-cancelled activities
Added test for verifying no double-cancel on heartbeats
1. Closes 

Fix double-resolve activity bug

---

Cargo.toml
src/machines/workflow_task_state_machine.rs
src/pollers/gateway.rs

A few slightly ugly changes needed for new tonic interceptor api
1. Closes 

Upgrade tonic and others

---

protos/local/workflow_activation.proto
protos/local/workflow_commands.proto
src/machines/mod.rs
src/machines/patch_state_machine.rs
src/machines/transition_coverage.rs
src/machines/workflow_machines.rs
src/protos/mod.rs
src/prototype_rust_sdk.rs
src/prototype_rust_sdk/workflow_context.rs
src/prototype_rust_sdk/workflow_future.rs
src/test_help/history_builder.rs
src/workflow/history_update.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/changes.rs
tests/integ_tests/workflow_tests/patches.rs

Fix all the change marker / version stuff to be consistent and call them patches.
Consistency with Node and future SDKs
1. Closes 
Existing / new tests

Naming consistency with node (use `patch` terminology)

---

src/protosext/mod.rs

Pagination was implemented but I missed removing this check because I could never get server to actually paginate in tests.
1. Closes 

Remove panic on pagination token which should've been removed before

---

.gitmodules
protos/api_upstream/.buildkite/Dockerfile
protos/api_upstream/.buildkite/pipeline.yml
protos/api_upstream/.github/CODEOWNERS
protos/api_upstream/.github/PULL_REQUEST_TEMPLATE.md
protos/api_upstream/Makefile
protos/api_upstream/README.md
protos/api_upstream/temporal/api/command/v1/message.proto
protos/api_upstream/temporal/api/common/v1/message.proto
protos/api_upstream/temporal/api/enums/v1/command_type.proto
protos/api_upstream/temporal/api/enums/v1/common.proto
protos/api_upstream/temporal/api/enums/v1/event_type.proto
protos/api_upstream/temporal/api/enums/v1/failed_cause.proto
protos/api_upstream/temporal/api/enums/v1/namespace.proto
protos/api_upstream/temporal/api/enums/v1/query.proto
protos/api_upstream/temporal/api/enums/v1/reset.proto
protos/api_upstream/temporal/api/enums/v1/task_queue.proto
protos/api_upstream/temporal/api/enums/v1/workflow.proto
protos/api_upstream/temporal/api/errordetails/v1/message.proto
protos/api_upstream/temporal/api/failure/v1/message.proto
protos/api_upstream/temporal/api/filter/v1/message.proto
protos/api_upstream/temporal/api/history/v1/message.proto
protos/api_upstream/temporal/api/namespace/v1/message.proto
protos/api_upstream/temporal/api/replication/v1/message.proto
protos/api_upstream/temporal/api/taskqueue/v1/message.proto
protos/api_upstream/temporal/api/version/v1/message.proto
protos/api_upstream/temporal/api/workflow/v1/message.proto
protos/api_upstream/temporal/api/workflowservice/v1/request_response.proto
protos/api_upstream/temporal/api/workflowservice/v1/service.proto

In title
I needed the latest versions of the API protos.

Update API protos subtree

---

src/errors.rs

These errors were not differentiable when just looking at logs
1. Closes 

Differentiate various grpc error messages

---

Cargo.toml
src/workflow/workflow_tasks/cache_manager.rs

Fixed unneeded copying of strings in LRU
1. Closes 

Update LRU dep and fix related todo

---

src/core_tests/workflow_tasks.rs
src/test_help/mod.rs

Just adding a test to confirm something I was unsure about. It works.

Added a test to verify we can handle multiple WFT timeouts in a row

---

Cargo.toml
src/worker/activities.rs
src/worker/activities/activity_heartbeat_manager.rs
src/worker/config.rs
src/worker/mod.rs
tests/integ_tests/workflow_tests/activities.rs

No need to merge yet, we'll use this commit hash to publish a patch for the TypeScript SDK.

Fix activity completion after heartbeat timeout hang

---

client/src/raw.rs
core/src/replay/mod.rs

Which can happen with partial history

Replay mock client wasn't allowing completes

---

core/Cargo.toml
core/src/workflow/driven_workflow.rs
core/src/workflow/machines/workflow_machines.rs
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/build.rs
sdk-core-protos/src/lib.rs

Added more attribs to the start workflow job
Exposes more information to lang SDK
1. Closes https://github.com/temporalio/sdk-core/issues/273

Add more attributes to StartWorkflow job

---

.buildkite/docker/Dockerfile
.buildkite/docker/docker-compose.yaml
core/src/core_tests/child_workflows.rs
core/src/core_tests/queries.rs
core/src/protosext/mod.rs
core/src/worker/activities/local_activities.rs
core/src/workflow/machines/signal_external_state_machine.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/workflow_tasks/mod.rs
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
sdk-core-protos/src/lib.rs
sdk/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_context/options.rs
sdk/src/workflow_future.rs
tests/integ_tests/workflow_tests/signals.rs

Passes headers to signals and queries appropriately
Headers good
1. Closes https://github.com/temporalio/sdk-core/issues/236
Added tests

Add headers to signals and queries

---

core/src/worker/mod.rs
core/src/workflow/machines/workflow_machines.rs
core/src/workflow/mod.rs
core/src/workflow/workflow_tasks/mod.rs
sdk-core-protos/src/lib.rs

Use display for most tracing lines
Avoid logging giant payloads, etc
1. Closes https://github.com/temporalio/sdk-core/issues/215

Impl Display for more things to avoid dumping big outputs

---

.buildkite/docker/Dockerfile
client/src/lib.rs
client/src/mocks.rs
client/src/retry.rs
core-api/src/worker.rs
core/src/core_tests/activity_tasks.rs
core/src/core_tests/mod.rs
core/src/pollers/poll_buffer.rs
core/src/protosext/mod.rs
core/src/worker/mod.rs
sdk-core-protos/src/history_info.rs

Enables setting the task-queue throttle parameter
Control activity execution rate
1. Closes 

Enable setting activity task queue throttle

---

client/src/lib.rs
core/src/lib.rs
tests/integ_tests/client_tests.rs

Called the new endpoint during client connect
Ensures server is healthy, and allows checking of capabilities to switch features (not currently used)
1. Closes https://github.com/temporalio/sdk-core/issues/290

Call get system info during client connection

---

client/src/lib.rs

Not adding a test here for lack of mock for the client.
@Sushisource will add mocks and the test in a future PR.

Ignore Unimplemented getSystemInfo response

---

core/src/workflow/workflow_tasks/concurrency_manager.rs

It turns out that even though the *inner* lock for a particular run is fine to hold across an await point, the *outer* lock on the whole map was also being held (which seems obvious in retrospect). If a write to the overall map came in while the inner await was pending, you'd get an ABA lock situation and deadlock everything.
Now the lock is behind an Arc to prevent holding the outer lock while accessing.
Deadlocks bad
1. Closes 
Added unit test. Repro load test provided by Roey in typescript also fixed.

Fix possible deadlock in machine concurrency manager

---

core/src/worker/activities/local_activities.rs

Discovered while writing integration tests for TS

Support non retryable errors in local activities

---

core/src/worker/mod.rs
core/src/workflow/machines/timer_state_machine.rs
core/src/workflow/workflow_tasks/cache_manager.rs
core/src/workflow/workflow_tasks/mod.rs
tests/load_tests.rs

This line is wrong either way. Trying to verify if this fixes a deadlock.

Fix hang waiting on cache slot

---

core/src/protosext/mod.rs
core/src/retry_logic.rs

Don't error when local activity options is None and make default initial interval 1 second

---

sdk/src/lib.rs

The sdk worker example doesn't run out of the box, had to make a couple tweaks
I wanted to test out the rust sdk
Create a test app locally, got it running and then pasted the code back into the docs.
N/A

Fix documentation for the sdk worker example

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/machines/workflow_machines.rs
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/lib.rs

Add new `history_length` field to workflow activations
Useful for deciding when to continue-as-new
1. Closes 
Instrumented a few existing tests. Re-uses a field which is already tested.

Expose history length in activations

---

core-api/src/lib.rs
core/src/core_tests/workers.rs
core/src/worker/workflow/mod.rs
sdk-core-protos/src/lib.rs

Don't panic if an empty evict reply comes in after shutdown is done

---

core/src/core_tests/queries.rs
core/src/worker/workflow/mod.rs

Not a fatal error
1. Closes https://github.com/temporalio/sdk-core/issues/305
UT

Fix panic on not-found when responding to legacy queries

---

client/src/lib.rs
core/src/worker/activities/activity_heartbeat_manager.rs
tests/main.rs

Fix possible panic during shutdown handling
Panic bad
1. Closes https://github.com/temporalio/sdk-core/issues/349

Don't panic on legit cancel errors inside heartbeat tasks on shutdown

---

core/src/worker/workflow/workflow_stream.rs

1. Closes https://github.com/temporalio/sdk-core/issues/361

Turn down log level for this line

---

client/src/lib.rs

Publicly expose the new traits

---

client/Cargo.toml
client/src/lib.rs
client/src/raw.rs
client/src/retry.rs
client/src/workflow_handle/mod.rs
core-api/src/worker.rs
core/Cargo.toml
core/src/core_tests/activity_tasks.rs
core/src/core_tests/workers.rs
core/src/lib.rs
core/src/pollers/poll_buffer.rs
core/src/replay/mod.rs
core/src/test_help/mod.rs
core/src/worker/activities.rs
core/src/worker/activities/activity_heartbeat_manager.rs
core/src/worker/client.rs
core/src/worker/mod.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
protos/api_upstream/temporal/api/batch/v1/message.proto
protos/api_upstream/temporal/api/enums/v1/batch_operation.proto
protos/api_upstream/temporal/api/taskqueue/v1/message.proto
protos/api_upstream/temporal/api/workflowservice/v1/request_response.proto
protos/api_upstream/temporal/api/workflowservice/v1/service.proto
sdk-core-protos/src/lib.rs

* Shuffled a bunch of stuff around to make the worker client easier to use / enable this feature
* Added bool flag to `WorkerConfig` for opting in to versioning feature
Will be needed to test versioning from a real lang SDK.
Relates to https://github.com/temporalio/sdk-features/issues/84

More client refactoring & add versioning-opt-in config flag

---

client/src/lib.rs
client/src/raw.rs

Do not overwrite per-call specified gRPC headers with the static every-call headers.
Just makes sense, yo.
1. Closes https://github.com/temporalio/sdk-core/issues/373
Added UT

Respect per-call gRPC headers

---

client/src/lib.rs
client/src/raw.rs
protos/grpc/health/v1/health.proto
sdk-core-protos/build.rs
sdk-core-protos/src/lib.rs

Added gRPC health service to client
1. Closes https://github.com/temporalio/sdk-core/issues/367
Added UTs

Add grpc health checking service/fns to client

---

client/src/lib.rs

Added proper health service getter
Original code had copy pasta using test service getter causing panic

Fix health service getter

---

core/src/core_tests/activity_tasks.rs
core/src/worker/mod.rs
core/src/worker/workflow/mod.rs

Don't dispatch eager activity if task queue is not the "current"

---

core/src/core_tests/activity_tasks.rs
core/src/worker/workflow/mod.rs

See https://github.com/temporalio/sdk-java/pull/1455

Limit max eager activities to 3

---

core/Cargo.toml
core/src/log_export.rs
core/src/worker/workflow/mod.rs
protos/local/temporal/sdk/core/workflow_commands/workflow_commands.proto
test-utils/src/lib.rs

Minor fixes etc
Was doing backlog cleanup, and one thing to help Chad debug
1. Closes https://github.com/temporalio/sdk-core/issues/310

Minor cleanup, small issue fixes

---

core/src/core_tests/queries.rs

Just verifying behavior which was associated with a TS bug. Worth keeping this UT.

Add a UT for new-query failure path

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/machines/workflow_machines.rs
sdk-core-protos/src/history_builder.rs

Ignore events which server indicates are explicitly ignorable by the SDK.
Future proofing
1. Part of https://github.com/temporalio/sdk-features/issues/143
Added UT

Ignorable events

---

core/src/worker/workflow/workflow_stream.rs

Debugify unknown run when evicting log

---

core/src/core_tests/activity_tasks.rs
core/src/test_help/mod.rs
core/src/worker/workflow/mod.rs

Same commit I just merged into the ts-release branch in #429

Don't request eager activities when worker started with no remote activities

---

core/src/lib.rs

Easier for python sdk
1. Closes 

Initialize subscriber in tokio threads for caller in CoreRuntime::new

---

bridge-ffi/src/wrappers.rs
core-api/src/telemetry.rs
core/src/telemetry/mod.rs
test-utils/src/lib.rs

See title
Useful to aggregate overwhelming metrics
1. Closes 

Make metrics export period for OTel configurable

---

core/src/worker/workflow/history_update.rs

Turns out server can in fact respond in some ways I did not think it could. Handle those situations and evict the workflow rather than panicking. 
1. Closes 
Added tests

Don't panic on unusual history fetching responses from server

---

fsm/rustfsm_procmacro/src/lib.rs

Fixed crate documentation example
1. Closes 

Fix FSM crate documentation

---

core/src/core_tests/local_activities.rs
core/src/worker/activities/local_activities.rs
core/src/worker/client.rs
core/src/worker/mod.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
protos/api_upstream/temporal/api/common/v1/message.proto
protos/api_upstream/temporal/api/history/v1/message.proto
protos/api_upstream/temporal/api/workflowservice/v1/request_response.proto
sdk-core-protos/src/lib.rs
tests/heavy_tests.rs

Attach nonfirst LA attempt count to WFT completes
Support metering changes
1. Closes 
Added two UTs

Attach nonfirst LA attempt count to WFTs

---

core/src/ephemeral_server/mod.rs
test-utils/src/lib.rs
tests/integ_tests/ephemeral_server_tests.rs
tests/integ_tests/workflow_tests/upsert_search_attrs.rs
tests/runner.rs

Temporal CLI ephemeral server

---

client/src/metrics.rs

Hard to use right now for lang side consumers

Fix non send/sync metric provider trait

---

core/src/worker/workflow/machines/workflow_machines.rs
tests/integ_tests/workflow_tests/patches.rs

Replaces https://github.com/temporalio/sdk-core/pull/504

Fix internal flags not always reflecting correct state

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/history_update.rs
test-utils/src/lib.rs

See big comment in changed code
Bugfix
1. Closes 
Added a unit test which repros the issue

Fix scenario where server sends page token pointing to empty page

---

core/src/worker/workflow/machines/child_workflow_state_machine.rs

Simple fix for miscategorized error

Fix child wf state machine returning fatal instead of NDE

---

tests/integ_tests/workflow_tests/activities.rs

Retry interval was too short, so sometimes retry would come in before the expected cancel.

Fix integ test that flaked sometimes

---

core/src/core_tests/workflow_tasks.rs
core/src/pollers/poll_buffer.rs
core/src/worker/workflow/wft_poller.rs

Avoid spinning up polling tasks until lang polls for the first time
This worked before, but the change for concurrent pollers meant the polling tasks would actually start going right away, this fixes that and makes sure we don't start getting tasks we can't do anything with.
1. Closes 
Added UT, existing tests.

Don't spin up pollers until first poll by lang

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/machines/workflow_machines.rs
protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/history_builder.rs
sdk-core-protos/src/lib.rs

Expose these attributes from WFT started events
Seeing these can be desirable when writing entity workflows
1. Closes https://github.com/temporalio/sdk-core/issues/564
Verified in UT

Expose history size in bytes and CAN suggestion

---

core/src/worker/workflow/machines/child_workflow_state_machine.rs

Fix typo in child workflow determinism error

---

core-api/src/telemetry/metrics.rs

Adds a cfg feature tag in the match statement
If you don't have the otel_impls feature and you're using the Rust SDK client, it will fail to compile.
1. Closes https://github.com/temporalio/sdk-core/issues/595
`cargo check`
1. Any docs updates needed?
None

Add missing cfg feature tag

---

core/src/telemetry/metrics.rs

Probably better than locking everything up if the buffer isn't being drained
1. Closes https://github.com/temporalio/sdk-core/issues/610

Log errors if metric buffer is full and drop calls rather than blocking

---

core/src/worker/workflow/machines/update_state_machine.rs
tests/integ_tests/update_tests.rs

Task failures after an update could trigger this path which would cause the sending of protocol messages that shouldn't have been sent. Fixes that.
Bug bad
1. Closes 

Fix bug where message replies to updates could be sent during replay

---

client/src/lib.rs
client/src/raw.rs
client/src/workflow_handle/mod.rs

Needed to enable the work on eager wf start

Make Client properly go through RawClient, expose more non-mut clients

---

core/src/worker/workflow/machines/activity_state_machine.rs

Second entry in the fuzzer trophy case

Fix canceling abandon mode not-yet-started activities

---

core/src/core_tests/activity_tasks.rs

This leftover line shouldn't be in here.

Remove leftover log enabling line

---

README.md

`--rebase=false` is needed for this command (we didn't notice as it was in some people's gitconfig)

Update subtree pull command

---

.github/workflows/per-pr.yml
core-api/src/errors.rs
core-api/src/worker.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
test-utils/src/lib.rs
tests/integ_tests/metrics_tests.rs
tests/integ_tests/workflow_tests.rs
tests/integ_tests/workflow_tests/eager.rs
tests/integ_tests/workflow_tests/signals.rs

Allow failing the WF instead of the task on nondeterminism errors
Useful setting
1. Closes https://github.com/temporalio/sdk-core/issues/656
Added integ tests

Enable failing WF on nondeterminism errors

---

.github/workflows/per-pr.yml
core/src/abstractions.rs
core/src/telemetry/mod.rs
core/src/test_help/mod.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_extraction.rs
fsm/rustfsm_procmacro/tests/trybuild/no_handle_conversions_require_into_fail.stderr
sdk-core-protos/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto
sdk-core-protos/src/lib.rs

Evictions now always come in their own activation
Simpler contract for lang
1. Closes 
Existing tests

Evictions in their own activations

---

core/src/telemetry/metrics.rs
core/src/worker/workflow/managed_run.rs

In title
User request, Go and Java have implemented
1. Closes https://github.com/temporalio/sdk-core/issues/730

Attach `failure_reason` tag to workflow task failures

---

core/src/core_tests/queries.rs
core/src/worker/workflow/workflow_stream.rs

Allows the buffer for WFTs that are waiting for a cache slot to hold more than one task per run id
Solves situation where multiple tasks can arrive containing legacy queries
1. Closes https://github.com/temporalio/sdk-core/issues/716
Expanded unit test

Allow buffering more than one WFT per run when at cache limit

---

core/src/ephemeral_server/mod.rs
tests/integ_tests/ephemeral_server_tests.rs

- When assigning ephemeral ports for use by Ephemeral Servers, on all platforms except macOS and Windows, immediately open a connection to that port, and force the connection into `TIME_WAIT` state. This avoids various race conditions that could happen due to the port being reallocated between the moment the port is obtained and the moment the server actually binds to that port.
- Added a test to confirm that it is possible to start multiple dev server concurrently; however, that test is currently skipped, as it will fail on Linux until temporalio/cli#564 gets released (presumably in 0.12.1). That can still be used locally by building CLI manually.

get-free-port: prevent duplicate ports on Linux

---

core/src/core_tests/updates.rs
core/src/protosext/protocol_messages.rs
core/src/worker/workflow/machines/update_state_machine.rs

Include original update request in accept/reject responses
Needed for server
1. Closes https://github.com/temporalio/sdk-core/issues/743
Added unit test, existing tests

Attach update request to responses

---

core/src/worker/mod.rs

Don't fail namespace validation check on unimplemented

---

core/src/worker/tuner.rs

Fix dumb oversight in last tuner options builder

---

client/src/retry.rs

For calls that can retry forever (polling), eventually start logging errors if retrying has been going on for a while
More obvious for users who have alerting set up on error lines
1. Closes https://github.com/temporalio/sdk-core/issues/704

Make grpc retries eventually turn into error messages

---

core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/machines/workflow_machines.rs

WFT look-ahead was not properly handling the fact that in a "logical WFT" which spans multiple individual WFTS we want to merge flags from more than just the immediate-next WFT. Fix that.
Bug
1. Closes 
Added UT

Fix issue with lookahead not properly seeing flags in multi-wft sequences

---

sdk/src/lib.rs
sdk/src/workflow_future.rs

This PR expands OpenTelemetry support in the Rust SDK. The workflow and activity futures get instrumented using tracing (similar to other places in the code).
To follow other SDKs such as the python one, the spans use "otel.name" (special keyword from `tracing-opentelemtry` to create a span name with the type name of the workflow/activity.
Currently, these futures get spawned and thus don't have a root span. To get a root span boilerplate code is required in all workflow and activity functions. To have less boilerplate and to follow the naming conventions more strictly first party support is desired.
I plan on expanding this with support for propagation.
This currently relies on internals of the `tracing-opentelemetry` crate (`otel.name` and `otel.kind` resource names). Also, this is …

sdk: create spans for RunWorkflow and RunActivity

---

core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/cancel_external_state_machine.rs
core/src/worker/workflow/machines/cancel_workflow_state_machine.rs
core/src/worker/workflow/machines/child_workflow_state_machine.rs
core/src/worker/workflow/machines/complete_workflow_state_machine.rs
core/src/worker/workflow/machines/continue_as_new_workflow_state_machine.rs
core/src/worker/workflow/machines/fail_workflow_state_machine.rs
core/src/worker/workflow/machines/modify_workflow_properties_state_machine.rs
core/src/worker/workflow/machines/patch_state_machine.rs
core/src/worker/workflow/machines/signal_external_state_machine.rs
core/src/worker/workflow/machines/timer_state_machine.rs
core/src/worker/workflow/machines/upsert_search_attributes_state_machine.rs
sdk-core-protos/protos/api_upstream/.github/workflows/trigger-api-go-update.yml
sdk-core-protos/protos/api_upstream/.gitmodules
sdk-core-protos/protos/api_upstream/openapi/openapiv2.json
sdk-core-protos/protos/api_upstream/openapi/openapiv3.yaml
sdk-core-protos/protos/api_upstream/temporal/api/command/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/failed_cause.proto
sdk-core-protos/protos/api_upstream/temporal/api/enums/v1/task_queue.proto
sdk-core-protos/protos/api_upstream/temporal/api/history/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/nexus/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/operatorservice/v1/service.proto
sdk-core-protos/protos/api_upstream/temporal/api/sdk/v1/enhanced_stack_trace.proto
sdk-core-protos/protos/api_upstream/temporal/api/sdk/v1/user_metadata.proto
sdk-core-protos/protos/api_upstream/temporal/api/sdk/v1/workflow_metadata.proto
sdk-core-protos/protos/api_upstream/temporal/api/taskqueue/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/workflow/v1/message.proto
sdk-core-protos/protos/api_upstream/temporal/api/workflowservice/v1/request_response.proto
sdk-core-protos/protos/api_upstream/temporal/api/workflowservice/v1/service.proto
sdk-core-protos/src/lib.rs

Updated protos from api upstream.

Update protos from upstream.

---

core/src/worker/workflow/history_update.rs
sdk/src/workflow_context.rs
sdk/src/workflow_context/options.rs
tests/heavy_tests.rs

Similar to #770 -- somehow missed this yesterday.

sdk: make ActivityOptions::task_queue an Option

---

client/src/lib.rs
client/src/raw.rs
tests/integ_tests/client_tests.rs

Attach `temporal-namespace` header to namespaced calls
Requested by cloud
1. Closes https://github.com/temporalio/sdk-core/issues/736
Integ test

Attach `temporal-namespace` header to namespace requests

---

Cargo.toml
client/Cargo.toml
client/src/metrics.rs
core/Cargo.toml
core/src/abstractions.rs
core/src/worker/slot_provider.rs
core/src/worker/tuner/resource_based.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/activity_state_machine.rs
core/src/worker/workflow/machines/cancel_external_state_machine.rs
core/src/worker/workflow/machines/child_workflow_state_machine.rs
core/src/worker/workflow/machines/local_activity_state_machine.rs
core/src/worker/workflow/machines/mod.rs
core/src/worker/workflow/machines/signal_external_state_machine.rs
core/src/worker/workflow/machines/update_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/machines/workflow_task_state_machine.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/workflow_stream.rs
fsm/rustfsm_procmacro/src/lib.rs

Dependencies upgrade

---

core/src/protosext/mod.rs
core/src/worker/activities/activity_task_poller_stream.rs
core/src/worker/slot_provider.rs
sdk-core-protos/src/lib.rs
sdk/src/lib.rs

At least check that activity tasks have a task token, to avoid user proxies tricking the SDK into thinking an empty poll response wasn't empty.
Custom proxy implementations breaking things.
1. Closes https://github.com/temporalio/sdk-core/issues/794
Existing tests

Basic validation of activity tasks

---

core/Cargo.toml
core/src/debug_client.rs
core/src/lib.rs
core/src/worker/mod.rs

Simple client to help languages interact with the vscode debug plugin.
Arguably this isn't really doing much, but, it's at least vaguely useful.

Client for VSCode Debug Plugin

---

core/Cargo.toml
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_extraction.rs
core/src/worker/workflow/workflow_stream.rs

Some simple lint fixes & dep updates for new Rust release

Lints for new Rust version

---

core-api/Cargo.toml
core-api/src/worker.rs
core/src/abstractions.rs
core/src/core_tests/workflow_tasks.rs
core/src/worker/activities.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
core/src/worker/tuner.rs
core/src/worker/tuner/fixed_size.rs
core/src/worker/tuner/resource_based.rs
core/src/worker/workflow/wft_extraction.rs
sdk-core-protos/protos/local/temporal/sdk/core/core_interface.proto

Unlocks https://github.com/temporalio/sdk-typescript/pull/1553 and other langs

Changes needed for lang-implementable slot suppliers

---

core/src/lib.rs
tests/integ_tests/metrics_tests.rs

Needed for Python custom slot suppliers

Allow langs to specify custom on-thread-start functions

---

core/src/ephemeral_server/mod.rs
test-utils/src/lib.rs
tests/integ_tests/ephemeral_server_tests.rs

Fixed a couple QoL bugs relating to server downloads
1. Closes https://github.com/temporalio/sdk-core/issues/551 and closes https://github.com/temporalio/sdk-core/issues/500
Existing and new tests

Ephemeral server fixes

---

sdk-core-protos/src/lib.rs

Fix nexus event rename breaking change in server

---

core/src/telemetry/otel.rs
tests/integ_tests/metrics_tests.rs

Fixed bucket overrides being applied in the wrong place
Bug
1. Closes https://github.com/temporalio/sdk-core/issues/873
Upgraded existing test

Apply histogram bucket overrides consistently

---

.cargo/config.toml
.github/workflows/per-pr.yml
AGENTS.md
core/Cargo.toml
core/src/ephemeral_server/mod.rs
core/src/internal_flags.rs
core/src/protosext/mod.rs
core/src/worker/activities.rs
core/src/worker/activities/local_activities.rs
core/src/worker/nexus.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/wft_poller.rs
core/src/worker/workflow/workflow_stream.rs
tests/fuzzy_workflow.rs
tests/runner.rs

Minor cleanup stuff (well, actually the recompile thing has been a serious PITA for some time)

Fix new clippy lints & integ test recompiles

---

client/src/lib.rs
client/src/metrics.rs
client/src/raw.rs
client/src/retry.rs
client/src/worker_registry/mod.rs
core-api/src/envconfig.rs
core-api/src/worker.rs
core/src/abstractions.rs
core/src/internal_flags.rs
core/src/pollers/poll_buffer.rs
core/src/protosext/mod.rs
core/src/telemetry/metrics.rs
core/src/worker/activities/activity_heartbeat_manager.rs
core/src/worker/activities/local_activities.rs
core/src/worker/mod.rs
core/src/worker/workflow/history_update.rs
core/src/worker/workflow/machines/nexus_operation_state_machine.rs
core/src/worker/workflow/machines/workflow_machines.rs
core/src/worker/workflow/managed_run.rs
core/src/worker/workflow/mod.rs
core/src/worker/workflow/wft_poller.rs
core/src/worker/workflow/workflow_stream.rs
sdk/src/lib.rs
sdk/src/workflow_context.rs
sdk/src/workflow_context/options.rs
test-utils/src/lib.rs
tests/cloud_tests.rs
tests/integ_tests/worker_tests.rs
tests/integ_tests/workflow_tests/nexus.rs

Auto fix if-let chains & other newer lints

---

core/src/worker/workflow/mod.rs
tests/cloud_tests.rs
tests/integ_tests/worker_tests.rs

Title
More clarity in error
1. Closes #918 

Update GRPC failure to new proto error

---

core/src/worker/mod.rs

Disable heartbeating for generic test initialization
Don't heartbeat on non-heartbeat tests. Heartbeat tests manually initialize heartbeating mechanism
1. Closes 

Fix heartbeat test flake

---

core-c-bridge/include/temporal-sdk-core-c-bridge.h
core-c-bridge/src/worker.rs

Added Nexus support for the C bridge

Nexus Support in C Bridge

---

core/src/core_tests/local_activities.rs
core/src/core_tests/workflow_tasks.rs
core/src/worker/workflow/mod.rs
tests/integ_tests/visibility_tests.rs
tests/integ_tests/workflow_tests/nexus.rs

Flake fixes

---

sdk/src/activity_context.rs
sdk/src/app_data.rs

Expose ActivityContext and AppData
Allows external crates to unit test their activities with context.
**1. Closes** [Issue 1011](https://github.com/temporalio/sdk-core/issues/1011)
**2. How was this tested:** Ran activities with context on an external create
**3. Any docs updates needed?** Nope

Issue 1011 - enable testing activities with context.

---

core/src/worker/activities/local_activities.rs
tests/integ_tests/worker_tests.rs

Title
1. Closes https://github.com/temporalio/sdk-core/issues/1016
Added a nice big new test

Fix local activity type wrong in custom slot supplier
